<!-- lab: desktop 2.157.879.0 -->

# Table.Transpose

Rows become columns.

```m
Table.Transpose(#table({"a", "b"}, {{1, 2}, {3, 4}}))
```

```text
#table(type table [Column1 = any, Column2 = any], {{1, 3}, {2, 4}})
```
