<!-- lab: desktop 2.157.879.0 -->

# Table.FromRows

One list per row.

```m
Table.FromRows({{1, "a"}, {2, "b"}}, {"n", "t"})
```

```text
#table(type table [n = any, t = any], {{1, "a"}, {2, "b"}})
```
