<!-- lab: desktop 2.157.879.0 -->

# Table.FromColumns

One list per column.

```m
Table.FromColumns({{1, 2}, {"a", "b"}}, {"n", "t"})
```

```text
#table(type table [n = any, t = any], {{1, "a"}, {2, "b"}})
```
