---
name: "Table.ReplaceRows"
category: "Table.Row operations"
returns: "table"
hosts: ["desktop"]
notes: false
examples: 1
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.ReplaceRows

```m
Table.ReplaceRows(table as table, offset as number, count as number, rows as list) as table
```

Replaces a specified number of rows, `count`, in the input `table` with the specified `rows`, beginning after the `offset`. The `rows` parameter is a list of records.

- `table`: The table where the replacement is performed.

- `offset`: The number of rows to skip before making the replacement.

- `count`: The number of rows to replace.

- `rows`: The list of row records to insert into the `table` at the location specified by the `offset`.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |
| `offset` | `number` | no |
| `count` | `number` | no |
| `rows` | `list` | no |

**Executed examples (1):** [examples/table-row-operations/table-replacerows.md](../../examples/table-row-operations/table-replacerows.md)

## Examples (engine metadata — not verified here)

Starting at position 1, replace 3 rows.

```m
Table.ReplaceRows(
    Table.FromRecords({
        [Column1 = 1],
        [Column1 = 2],
        [Column1 = 3],
        [Column1 = 4],
        [Column1 = 5]
    }),
    1,
    3,
    {[Column1 = 6], [Column1 = 7]}
)
```

Stated result:

```m
Table.FromRecords({
    [Column1 = 1],
    [Column1 = 6],
    [Column1 = 7],
    [Column1 = 5]
})
```
