---
name: "Table.Min"
category: "Table.Ordering"
returns: "any"
hosts: ["desktop"]
notes: false
examples: 1
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.Min

```m
Table.Min(table as table, comparisonCriteria as any, optional default as any) as any
```

Returns the smallest row in the `table`, given the `comparisonCriteria`. If the table is empty, the optional `default` value is returned.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |
| `comparisonCriteria` | `any` | no |
| `default` | `any` | yes |

**Executed examples (1):** [examples/table-ordering/table-min.md](../../examples/table-ordering/table-min.md)

## Examples (engine metadata — not verified here)

Find the row with the smallest value in column [a] in the table.

```m
Table.Min(
    Table.FromRecords({
        [a = 2, b = 4],
        [a = 6, b = 8]
    }),
    "a"
)
```

Stated result:

```m
[a = 2, b = 4]
```

Find the row with the smallest value in column [a] in the table. Return -1 if empty.

```m
Table.Min(#table({"a"}, {}), "a", -1)
```

Stated result:

```m
-1
```
