---
name: "Table.ContainsAny"
category: "Table.Membership"
returns: "logical"
hosts: ["desktop"]
notes: false
examples: 1
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.ContainsAny

```m
Table.ContainsAny(table as table, rows as list, optional equationCriteria as any) as logical
```

Indicates whether any the specified records in the list of records `rows`, appear as rows in the `table`.
An optional parameter `equationCriteria` may be specified to control comparison between the rows of the table.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |
| `rows` | `list` | no |
| `equationCriteria` | `any` | yes |

**Executed examples (1):** [examples/table-membership/table-containsany.md](../../examples/table-membership/table-containsany.md)

## Examples (engine metadata — not verified here)

Determine if the table `({[a = 1, b = 2], [a = 3, b = 4]})` contains the rows `[a = 1, b = 2]` or `[a = 3, b = 5]`.

```m
Table.ContainsAny(
    Table.FromRecords({
        [a = 1, b = 2],
        [a = 3, b = 4]
    }),
    {
        [a = 1, b = 2],
        [a = 3, b = 5]
    }
)
```

Stated result:

```m
true
```

Determine if the table `({[a = 1, b = 2], [a = 3, b = 4]})` contains the rows `[a = 1, b = 3]` or `[a = 3, b = 5]`.

```m
Table.ContainsAny(
    Table.FromRecords({
        [a = 1, b = 2],
        [a = 3, b = 4]
    }),
    {
        [a = 1, b = 3],
        [a = 3, b = 5]
    }
)
```

Stated result:

```m
false
```

Determine if the table `(Table.FromRecords({[a = 1, b = 2], [a = 3, b = 4]}))` contains the rows `[a = 1, b = 3]` or `[a = 3, b = 5]` comparing only the column [a].

```m
Table.ContainsAny(
    Table.FromRecords({
        [a = 1, b = 2],
        [a = 3, b = 4]
    }),
    {
        [a = 1, b = 3],
        [a = 3, b = 5]
    },
    "a"
)
```

Stated result:

```m
true
```
