---
name: "Table.TransformColumnNames"
category: "Table.Column operations"
returns: "table"
hosts: ["desktop"]
notes: false
examples: 1
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.TransformColumnNames

```m
Table.TransformColumnNames(table as table, nameGenerator as function, optional options as nullable record) as table
```

Transforms column names by using the given `nameGenerator` function. Valid options:

`MaxLength` specifies the maximum length of new column names. If the given function results with a longer column name, the long name will be trimmed.

`Comparer` is used to control the comparison while generating new column names. Comparers can be used to provide case-insensitive or culture and locale-aware comparisons.

The following built-in comparers are available in the formula language:

- `Comparer.Ordinal`: Used to perform an exact ordinal comparison

- `Comparer.OrdinalIgnoreCase`: Used to perform an exact ordinal case-insensitive comparison

- `Comparer.FromCulture`: Used to perform a culture-aware comparison

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |
| `nameGenerator` | `function` | no |
| `options` | `nullable record` | yes |

**Executed examples (1):** [examples/table-column-operations/table-transformcolumnnames.md](../../examples/table-column-operations/table-transformcolumnnames.md)

## Examples (engine metadata — not verified here)

Remove the `#(tab)` character from column names

```m
Table.TransformColumnNames(Table.FromRecords({[#"Col#(tab)umn" = 1]}), Text.Clean)
```

Stated result:

```m
Table.FromRecords({[Column = 1]})
```

Transform column names to generate case-insensitive names of length 6.

```m
Table.TransformColumnNames(
    Table.FromRecords({[ColumnNum = 1, cOlumnnum = 2, coLumnNUM = 3]}),
    Text.Clean,
    [MaxLength = 6, Comparer = Comparer.OrdinalIgnoreCase]
)
```

Stated result:

```m
Table.FromRecords({[Column = 1, cOlum1 = 2, coLum2 = 3]})
```
