---
name: "Table.Keys"
category: "Table.Transformation"
returns: "list"
hosts: ["desktop"]
notes: false
examples: 1
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.Keys

```m
Table.Keys(table as table) as list
```

Returns the keys of the specified table.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |

**Executed examples (1):** [examples/table-transformation/table-keys.md](../../examples/table-transformation/table-keys.md)

## Examples (engine metadata — not verified here)

Get the list of keys for a table.

```m
let
    table = Table.FromRecords({
        [Id = 1, Name = "Hello There"],
        [Id = 2, Name = "Good Bye"]
    }),
    tableWithKeys = Table.AddKey(table, {"Id"}, true),
    keys = Table.Keys(tableWithKeys)
in
    keys
```

Stated result:

```m
{[Columns = {"Id"}, Primary = true]}
```
