---
name: "Table.FillDown"
category: "Table.Transformation"
returns: "table"
hosts: ["desktop"]
notes: false
examples: 1
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.FillDown

```m
Table.FillDown(table as table, columns as list) as table
```

Returns a table from the `table` specified where the value of a previous cell is propagated to the null-valued cells below in the `columns` specified.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |
| `columns` | `list` | no |

**Executed examples (1):** [examples/table-transformation/table-filldown.md](../../examples/table-transformation/table-filldown.md)

## Examples (engine metadata — not verified here)

Return a table with the null values in column [Place] filled with the value above them from the table.

```m
Table.FillDown(
    Table.FromRecords({
        [Place = 1, Name = "Bob"],
        [Place = null, Name = "John"],
        [Place = 2, Name = "Brad"],
        [Place = 3, Name = "Mark"],
        [Place = null, Name = "Tom"],
        [Place = null, Name = "Adam"]
    }),
    {"Place"}
)
```

Stated result:

```m
Table.FromRecords({
    [Place = 1, Name = "Bob"],
    [Place = 1, Name = "John"],
    [Place = 2, Name = "Brad"],
    [Place = 3, Name = "Mark"],
    [Place = 3, Name = "Tom"],
    [Place = 3, Name = "Adam"]
})
```
