---
name: "Table.LastN"
category: "Table.Row operations"
returns: "table"
hosts: ["desktop"]
notes: false
examples: 0
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.LastN

```m
Table.LastN(table as table, countOrCondition as any) as table
```

Returns the last row(s) from the table, `table`, depending on the value of `countOrCondition`:

- If `countOrCondition` is a number, that many rows will be returned starting from position (end - `countOrCondition`).

- If `countOrCondition` is a condition, the rows that meet the condition will be returned in ascending position until a row does not meet the condition.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |
| `countOrCondition` | `any` | no |

## Examples (engine metadata — not verified here)

Find the last two rows of the table.

```m
Table.LastN(
    Table.FromRecords({
        [CustomerID = 1, Name = "Bob", Phone = "123-4567"],
        [CustomerID = 2, Name = "Jim", Phone = "987-6543"],
        [CustomerID = 3, Name = "Paul", Phone = "543-7890"]
    }),
    2
)
```

Stated result:

```m
Table.FromRecords({
    [CustomerID = 2, Name = "Jim", Phone = "987-6543"],
    [CustomerID = 3, Name = "Paul", Phone = "543-7890"]
})
```

Find the last rows where [a] > 0 in the table.

```m
Table.LastN(
    Table.FromRecords({
        [a = -1, b = -2],
        [a = 3, b = 4],
        [a = 5, b = 6]
    }),
    each _ [a] > 0
)
```

Stated result:

```m
Table.FromRecords({
    [a = 3, b = 4],
    [a = 5, b = 6]
})
```
