---
name: "Table.RemoveFirstN"
category: "Table.Row operations"
returns: "table"
hosts: ["desktop"]
notes: false
examples: 0
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.RemoveFirstN

```m
Table.RemoveFirstN(table as table, optional countOrCondition as any) as table
```

Returns a table that does not contain the first specified number of rows, `countOrCondition`, of the table `table`.
The number of rows removed depends on the optional parameter `countOrCondition`.

- If `countOrCondition` is omitted only the first row is removed.

- If `countOrCondition` is a number, that many rows (starting at the top) will be removed.

- If `countOrCondition` is a condition, the rows that meet the condition will be removed until a row does not meet the condition.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |
| `countOrCondition` | `any` | yes |

## Examples (engine metadata — not verified here)

Remove the first row of the table.

```m
Table.RemoveFirstN(
    Table.FromRecords({
        [CustomerID = 1, Name = "Bob", Phone = "123-4567"],
        [CustomerID = 2, Name = "Jim", Phone = "987-6543"],
        [CustomerID = 3, Name = "Paul", Phone = "543-7890"],
        [CustomerID = 4, Name = "Ringo", Phone = "232-1550"]
    }),
    1
)
```

Stated result:

```m
Table.FromRecords({
    [CustomerID = 2, Name = "Jim", Phone = "987-6543"],
    [CustomerID = 3, Name = "Paul", Phone = "543-7890"],
    [CustomerID = 4, Name = "Ringo", Phone = "232-1550"]
})
```

Remove the first two rows of the table.

```m
Table.RemoveFirstN(
    Table.FromRecords({
        [CustomerID = 1, Name = "Bob", Phone = "123-4567"],
        [CustomerID = 2, Name = "Jim", Phone = "987-6543"],
        [CustomerID = 3, Name = "Paul", Phone = "543-7890"],
        [CustomerID = 4, Name = "Ringo", Phone = "232-1550"]
    }),
    2
)
```

Stated result:

```m
Table.FromRecords({
    [CustomerID = 3, Name = "Paul", Phone = "543-7890"],
    [CustomerID = 4, Name = "Ringo", Phone = "232-1550"]
})
```

Remove the first rows where [CustomerID] <=2 of the table.

```m
Table.RemoveFirstN(
    Table.FromRecords({
        [CustomerID = 1, Name = "Bob", Phone = "123-4567"],
        [CustomerID = 2, Name = "Jim", Phone = "987-6543"],
        [CustomerID = 3, Name = "Paul", Phone = "543-7890"],
        [CustomerID = 4, Name = "Ringo", Phone = "232-1550"]
    }),
    each [CustomerID] <= 2
)
```

Stated result:

```m
Table.FromRecords({
    [CustomerID = 3, Name = "Paul", Phone = "543-7890"],
    [CustomerID = 4, Name = "Ringo", Phone = "232-1550"]
})
```
