---
name: "Table.ToList"
category: "Table.Conversions"
returns: "list"
hosts: ["desktop"]
notes: false
examples: 0
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.ToList

```m
Table.ToList(table as table, optional combiner as nullable function) as list
```

Converts a table into a list by applying the specified combining function to each row of values in the table.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |
| `combiner` | `nullable function` | yes |

## Examples (engine metadata — not verified here)

Combine the text of each row with a comma.

```m
Table.ToList(
    Table.FromRows({
        {Number.ToText(1), "Bob", "123-4567"},
        {Number.ToText(2), "Jim", "987-6543"},
        {Number.ToText(3), "Paul", "543-7890"}
    }),
    Combiner.CombineTextByDelimiter(",")
)
```

Stated result:

```m
{"1,Bob,123-4567", "2,Jim,987-6543", "3,Paul,543-7890"}
```
