---
name: "Table.SelectRowsWithErrors"
category: "Table.Row operations"
returns: "table"
hosts: ["desktop"]
notes: false
examples: 1
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.SelectRowsWithErrors

```m
Table.SelectRowsWithErrors(table as table, optional columns as nullable list) as table
```

Returns a table with only those rows of the input table that contain an error in at least one of the cells. If a columns list is specified, then only the cells in the specified columns are inspected for errors.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |
| `columns` | `nullable list` | yes |

**Executed examples (1):** [examples/table-row-operations/table-selectrowswitherrors.md](../../examples/table-row-operations/table-selectrowswitherrors.md)

## Examples (engine metadata — not verified here)

Select names of customers with errors in their rows.

```m
Table.SelectRowsWithErrors(
    Table.FromRecords({
        [CustomerID = ..., Name = "Bob", Phone = "123-4567"],
        [CustomerID = 2, Name = "Jim", Phone = "987-6543"],
        [CustomerID = 3, Name = "Paul", Phone = "543-7890"],
        [CustomerID = 4, Name = "Ringo", Phone = "232-1550"]
    })
)[Name]
```

Stated result:

```m
{"Bob"}
```
