---
name: "Table.Unpivot"
category: "Table.Column operations"
returns: "table"
hosts: ["desktop"]
notes: false
examples: 0
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.Unpivot

```m
Table.Unpivot(table as table, pivotColumns as list, attributeColumn as text, valueColumn as text) as table
```

Translates a set of columns in a table into attribute-value pairs, combined with the rest of the values in each row.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |
| `pivotColumns` | `list` | no |
| `attributeColumn` | `text` | no |
| `valueColumn` | `text` | no |

## Examples (engine metadata — not verified here)

Take the columns "a", "b", and "c" in the table `({[ key = "x", a = 1, b = null, c = 3 ], [ key = "y", a = 2, b = 4, c = null ]})` and unpivot them into attribute-value pairs.

```m
Table.Unpivot(
    Table.FromRecords({
        [key = "x", a = 1, b = null, c = 3],
        [key = "y", a = 2, b = 4, c = null]
    }),
    {"a", "b", "c"},
    "attribute",
    "value"
)
```

Stated result:

```m
Table.FromRecords({
    [key = "x", attribute = "a", value = 1],
    [key = "x", attribute = "c", value = 3],
    [key = "y", attribute = "a", value = 2],
    [key = "y", attribute = "b", value = 4]
})
```
