---
name: "Table.SingleRow"
category: "Table.Row operations"
returns: "record"
hosts: ["desktop"]
notes: false
examples: 1
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.SingleRow

```m
Table.SingleRow(table as table) as record
```

Returns the single row in the one row `table`. If the `table` has more than one row, an error is raised.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |

**Executed examples (1):** [examples/table-row-operations/table-singlerow.md](../../examples/table-row-operations/table-singlerow.md)

## Examples (engine metadata — not verified here)

Return the single row in the table.

```m
Table.SingleRow(Table.FromRecords({[CustomerID = 1, Name = "Bob", Phone = "123-4567"]}))
```

Stated result:

```m
[CustomerID = 1, Name = "Bob", Phone = "123-4567"]
```
