---
name: "Table.PrefixColumns"
category: "Table.Column operations"
returns: "table"
hosts: ["desktop"]
notes: false
examples: 1
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.PrefixColumns

```m
Table.PrefixColumns(table as table, prefix as text) as table
```

Returns a table where all the column names from the `table` provided are prefixed with the given text, `prefix`, plus a period in the form `prefix.ColumnName`.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |
| `prefix` | `text` | no |

**Executed examples (1):** [examples/table-column-operations/table-prefixcolumns.md](../../examples/table-column-operations/table-prefixcolumns.md)

## Examples (engine metadata — not verified here)

Prefix the columns with "MyTable" in the table.

```m
Table.PrefixColumns(
    Table.FromRecords({[CustomerID = 1, Name = "Bob", Phone = "123-4567"]}),
    "MyTable"
)
```

Stated result:

```m
Table.FromRecords({[MyTable.CustomerID = 1, MyTable.Name = "Bob", MyTable.Phone = "123-4567"]})
```
