---
name: "Table.HasColumns"
category: "Table.Column operations"
returns: "logical"
hosts: ["desktop"]
notes: false
examples: 1
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.HasColumns

```m
Table.HasColumns(table as table, columns as any) as logical
```

Indicates whether the `table` contains the specified column(s), `columns`. Returns `true` if the table contains the column(s), `false` otherwise.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |
| `columns` | `any` | no |

**Executed examples (1):** [examples/table-column-operations/table-hascolumns.md](../../examples/table-column-operations/table-hascolumns.md)

## Examples (engine metadata — not verified here)

Determine if the table has the column [Name].

```m
Table.HasColumns(
    Table.FromRecords({
        [CustomerID = 1, Name = "Bob", Phone = "123-4567"],
        [CustomerID = 2, Name = "Jim", Phone = "987-6543"],
        [CustomerID = 3, Name = "Paul", Phone = "543-7890"],
        [CustomerID = 4, Name = "Ringo", Phone = "232-1550"]
    }),
    "Name"
)
```

Stated result:

```m
true
```

Find if the table has the column [Name] and [PhoneNumber].

```m
Table.HasColumns(
    Table.FromRecords({
        [CustomerID = 1, Name = "Bob", Phone = "123-4567"],
        [CustomerID = 2, Name = "Jim", Phone = "987-6543"],
        [CustomerID = 3, Name = "Paul", Phone = "543-7890"],
        [CustomerID = 4, Name = "Ringo", Phone = "232-1550"]
    }),
    {"Name", "PhoneNumber"}
)
```

Stated result:

```m
false
```
