---
name: "Table.ExpandRecordColumn"
category: "Table.Transformation"
returns: "table"
hosts: ["desktop"]
notes: false
examples: 1
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.ExpandRecordColumn

```m
Table.ExpandRecordColumn(table as table, column as text, fieldNames as list, optional newColumnNames as nullable list) as table
```

Given the `column` of records in the input `table`, creates a table with a column for each field in the record. Optionally, `newColumnNames` may be specified to ensure unique names for the columns in the new table.

- `table`: The original table with the record column to expand.

- `column`: The column to expand.

- `fieldNames`: The list of fields to expand into columns in the table.

- `newColumnNames`: The list of column names to give the new columns. The new column names cannot duplicate any column in the new table.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |
| `column` | `text` | no |
| `fieldNames` | `list` | no |
| `newColumnNames` | `nullable list` | yes |

**Executed examples (1):** [examples/table-transformation/table-expandrecordcolumn.md](../../examples/table-transformation/table-expandrecordcolumn.md)

## Examples (engine metadata — not verified here)

Expand column [a] in the table `({[a = [aa = 1, bb = 2, cc = 3], b = 2]})` into 3 columns "aa", "bb" and "cc".

```m
Table.ExpandRecordColumn(
    Table.FromRecords({
        [
            a = [aa = 1, bb = 2, cc = 3],
            b = 2
        ]
    }),
    "a",
    {"aa", "bb", "cc"}
)
```

Stated result:

```m
Table.FromRecords({[aa = 1, bb = 2, cc = 3, b = 2]})
```
