---
name: "Table.PositionOfAny"
category: "Table.Membership"
returns: "any"
hosts: ["desktop"]
notes: false
examples: 1
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.PositionOfAny

```m
Table.PositionOfAny(table as table, rows as list, optional occurrence as nullable number, optional equationCriteria as any) as any
```

Returns the row(s) position(s) from the `table` of the first occurrence of the list of `rows`. Returns -1 if no occurrence is found.

- `table`: The input table.

- `rows`: The list of rows in the table to find the positions of.

- `occurrence`: *(Optional)* Specifies which occurrences of the row to return.

- `equationCriteria`: *(Optional)* Controls the comparison between the table rows.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |
| `rows` | `list` | no |
| `occurrence` | `nullable number` | yes |
| `equationCriteria` | `any` | yes |

**Executed examples (1):** [examples/table-membership/table-positionofany.md](../../examples/table-membership/table-positionofany.md)

## Examples (engine metadata — not verified here)

Find the position of the first occurrence of [a = 2, b = 4] or [a = 6, b = 8] in the table `({[a = 2, b = 4], [a = 6, b = 8], [a = 2, b = 4], [a = 1, b = 4]})`.

```m
Table.PositionOfAny(
    Table.FromRecords({
        [a = 2, b = 4],
        [a = 1, b = 4],
        [a = 2, b = 4],
        [a = 1, b = 4]
    }),
    {
        [a = 2, b = 4],
        [a = 6, b = 8]
    }
)
```

Stated result:

```m
0
```

Find the position of all the occurrences of [a = 2, b = 4] or [a = 6, b = 8] in the table `({[a = 2, b = 4], [a = 6, b = 8], [a = 2, b = 4], [a = 1, b = 4]}`.

```m
Table.PositionOfAny(
    Table.FromRecords({
        [a = 2, b = 4],
        [a = 6, b = 8],
        [a = 2, b = 4],
        [a = 1, b = 4]
    }),
    {
        [a = 2, b = 4],
        [a = 6, b = 8]
    },
    Occurrence.All
)
```

Stated result:

```m
{0, 1, 2}
```
