---
name: "Table.ClearDown"
category: "Table.Transformation"
returns: "table"
hosts: ["desktop"]
notes: false
examples: 0
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.ClearDown

```m
Table.ClearDown(table as table, columns as list) as table
```

Replaces the specified `columns` with null when all their values are repeated from the previous row.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |
| `columns` | `list` | no |

## Examples (engine metadata — not verified here)

Clear the Region and Place columns when they're both repeated.

```m
Table.ClearDown(
    Table.FromRecords({
        [Region = "West", Place = 1, Name = "Bob"],
        [Region = "West", Place = 1, Name = "John"],
        [Region = "West", Place = 2, Name = "Brad"],
        [Region = "East", Place = 3, Name = "Mark"],
        [Region = "East", Place = 3, Name = "Tom"]
    }),
    {"Region", "Place"}
)
```

Stated result:

```m
Table.FromRecords({
    [Region = "West", Place = 1, Name = "Bob"],
    [Region = null, Place = null, Name = "John"],
    [Region = "West", Place = 2, Name = "Brad"],
    [Region = "East", Place = 3, Name = "Mark"],
    [Region = null, Place = null, Name = "Tom"]
})
```
