---
name: "Table.Last"
category: "Table.Row operations"
returns: "any"
hosts: ["desktop"]
notes: false
examples: 1
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.Last

```m
Table.Last(table as table, optional default as any) as any
```

Returns the last row of the `table` or an optional default value, `default`, if the table is empty.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |
| `default` | `any` | yes |

**Executed examples (1):** [examples/table-row-operations/table-last.md](../../examples/table-row-operations/table-last.md)

## Examples (engine metadata — not verified here)

Find the last row of the table.

```m
Table.Last(
    Table.FromRecords({
        [CustomerID = 1, Name = "Bob", Phone = "123-4567"],
        [CustomerID = 2, Name = "Jim", Phone = "987-6543"],
        [CustomerID = 3, Name = "Paul", Phone = "543-7890"]
    })
)
```

Stated result:

```m
[CustomerID = 3, Name = "Paul", Phone = "543-7890"]
```

Find the last row of the table `({})` or return [a = 0, b = 0] if empty.

```m
Table.Last(Table.FromRecords({}), [a = 0, b = 0])
```

Stated result:

```m
[a = 0, b = 0]
```
