---
name: "Table.MinN"
category: "Table.Ordering"
returns: "table"
hosts: ["desktop"]
notes: false
examples: 0
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.MinN

```m
Table.MinN(table as table, comparisonCriteria as any, countOrCondition as any) as table
```

Returns the smallest row(s) in the `table`, given the `comparisonCriteria`. After the rows are sorted, the `countOrCondition` parameter must be specified to further filter the result. Note the sorting algorithm cannot guarantee a fixed sorted result. The `countOrCondition` parameter can take multiple forms:

- If a number is specified, a list of up to `countOrCondition` items in ascending order is returned.

- If a condition is specified, a list of items that initially meet the condition is returned. Once an item fails the condition, no further items are considered.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |
| `comparisonCriteria` | `any` | no |
| `countOrCondition` | `any` | no |

## Examples (engine metadata — not verified here)

Find the row with the smallest value in column [a] with the condition [a] < 3, in the table. The rows are sorted before the filter is applied.

```m
Table.MinN(
    Table.FromRecords({
        [a = 2, b = 4],
        [a = 0, b = 0],
        [a = 6, b = 4]
    }),
    "a",
    each [a] < 3
)
```

Stated result:

```m
Table.FromRecords({
    [a = 0, b = 0],
    [a = 2, b = 4]
})
```

Find the row with the smallest value in column [a] with the condition [b] < 0, in the table. The rows are sorted before the filter is applied.

```m
Table.MinN(
    Table.FromRecords({
        [a = 2, b = 4],
        [a = 8, b = 0],
        [a = 6, b = 2]
    }),
    "a",
    each [b] < 0
)
```

Stated result:

```m
Table.FromRecords({})
```
