---
name: "Table.ColumnsOfType"
category: "Table.Column operations"
returns: "list"
hosts: ["desktop"]
notes: false
examples: 0
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.ColumnsOfType

```m
Table.ColumnsOfType(table as table, listOfTypes as list) as list
```

Returns a list with the names of the columns from table `table` that match the types specified in `listOfTypes`.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |
| `listOfTypes` | `list` | no |

## Examples (engine metadata — not verified here)

Return the names of columns of type Number.Type from the table.

```m
Table.ColumnsOfType(
    Table.FromRecords(
        {[a = 1, b = "hello"]},
        type table[a = Number.Type, b = Text.Type]
    ),
    {type number}
)
```

Stated result:

```m
{"a"}
```
