---
name: "Table.SelectColumns"
category: "Table.Column operations"
returns: "table"
hosts: ["desktop"]
notes: false
examples: 1
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.SelectColumns

```m
Table.SelectColumns(table as table, columns as any, optional missingField as nullable number) as table
```

Returns the `table` with only the specified `columns`.

- `table`: The provided table.

- `columns`: The list of columns from the table `table` to return. Columns in the returned table are in the order listed in `columns`.

- `missingField`: *(Optional)* What to do if the column does not exist. Example: `MissingField.UseNull` or `MissingField.Ignore`.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |
| `columns` | `any` | no |
| `missingField` | `nullable number` | yes |

**Executed examples (1):** [examples/table-column-operations/table-selectcolumns.md](../../examples/table-column-operations/table-selectcolumns.md)

## Examples (engine metadata — not verified here)

Only include column [Name].

```m
Table.SelectColumns(
    Table.FromRecords({
        [CustomerID = 1, Name = "Bob", Phone = "123-4567"],
        [CustomerID = 2, Name = "Jim", Phone = "987-6543"],
        [CustomerID = 3, Name = "Paul", Phone = "543-7890"],
        [CustomerID = 4, Name = "Ringo", Phone = "232-1550"]
    }),
    "Name"
)
```

Stated result:

```m
Table.FromRecords({
    [Name = "Bob"],
    [Name = "Jim"],
    [Name = "Paul"],
    [Name = "Ringo"]
})
```

Only include columns [CustomerID] and [Name].

```m
Table.SelectColumns(
    Table.FromRecords({[CustomerID = 1, Name = "Bob", Phone = "123-4567"]}),
    {"CustomerID", "Name"}
)
```

Stated result:

```m
Table.FromRecords({[CustomerID = 1, Name = "Bob"]})
```

If the included column does not exist, the default result is an error.

```m
Table.SelectColumns(
    Table.FromRecords({[CustomerID = 1, Name = "Bob", Phone = "123-4567"]}),
    "NewColumn"
)
```

Stated result:

```m
[Expression.Error] The field 'NewColumn' of the record wasn't found.
```

If the included column does not exist, option `MissingField.UseNull` creates a column of null values.

```m
Table.SelectColumns(
    Table.FromRecords({[CustomerID = 1, Name = "Bob", Phone = "123-4567"]}),
    {"CustomerID", "NewColumn"},
    MissingField.UseNull
)
```

Stated result:

```m
Table.FromRecords({[CustomerID = 1, NewColumn = null]})
```
