---
name: "Table.ReorderColumns"
category: "Table.Column operations"
returns: "table"
hosts: ["desktop"]
notes: false
examples: 1
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.ReorderColumns

```m
Table.ReorderColumns(table as table, columnOrder as list, optional missingField as nullable number) as table
```

Returns a table from the input `table`, with the columns in the order specified by `columnOrder`. Columns that are not specified in the list will not be reordered.
If the column doesn't exist, an error is raised unless the optional parameter `missingField` specifies an alternative (eg. `MissingField.UseNull` or `MissingField.Ignore`).

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |
| `columnOrder` | `list` | no |
| `missingField` | `nullable number` | yes |

**Executed examples (1):** [examples/table-column-operations/table-reordercolumns.md](../../examples/table-column-operations/table-reordercolumns.md)

## Examples (engine metadata — not verified here)

Switch the order of the columns [Phone] and [Name] in the table.

```m
Table.ReorderColumns(
    Table.FromRecords({[CustomerID = 1, Phone = "123-4567", Name = "Bob"]}),
    {"Name", "Phone"}
)
```

Stated result:

```m
Table.FromRecords({[CustomerID = 1, Name = "Bob", Phone = "123-4567"]})
```

Switch the order of the columns [Phone] and [Address] or use "MissingField.Ignore" in the table. It doesn't change the table because column [Address] doesn't exist.

```m
Table.ReorderColumns(
    Table.FromRecords({[CustomerID = 1, Name = "Bob", Phone = "123-4567"]}),
    {"Phone", "Address"},
    MissingField.Ignore
)
```

Stated result:

```m
Table.FromRecords({[CustomerID = 1, Name = "Bob", Phone = "123-4567"]})
```
