---
name: "Table.Distinct"
category: "Table.Membership"
returns: "table"
hosts: ["desktop"]
notes: true
examples: 1
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.Distinct

```m
Table.Distinct(table as table, optional equationCriteria as any) as table
```

Removes duplicate rows from the table.
An optional parameter, `equationCriteria`, specifies which columns of the table are tested for duplication. If `equationCriteria` is not specified, all columns are tested.

Because Power Query sometimes offloads certain operations to backend data sources (known as "folding"), and also sometimes optimizes queries by
skipping operations that aren't strictly necessary, in general there's no guarantee which specific duplicate will be preserved.
For example, you can't assume that the first row with a unique set of column values will remain, and rows further down in the table will be removed.
If you want the duplicate removal to behave predictably, first buffer the table using `Table.Buffer`.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |
| `equationCriteria` | `any` | yes |

**Field note:** [`notes/table-distinct.md`](../../notes/table-distinct.md)

**Executed examples (1):** [examples/table-membership/table-distinct.md](../../examples/table-membership/table-distinct.md)

## Examples (engine metadata — not verified here)

Remove the duplicate rows from the table.

```m
Table.Distinct(
    Table.FromRecords({
        [a = "A", b = "a"],
        [a = "B", b = "b"],
        [a = "A", b = "a"]
    })
)
```

Stated result:

```m
Table.FromRecords({
    [a = "A", b = "a"],
    [a = "B", b = "b"]
})
```

Remove the duplicate rows from column [b] in the table `({[a = "A", b = "a"], [a = "B", b = "a"], [a = "A", b = "b"]})`.

```m
Table.Distinct(
    Table.FromRecords({
        [a = "A", b = "a"],
        [a = "B", b = "a"],
        [a = "A", b = "b"]
    }),
    "b"
)
```

Stated result:

```m
Table.FromRecords({
    [a = "A", b = "a"],
    [a = "A", b = "b"]
})
```
