---
name: "Table.RemoveRowsWithErrors"
category: "Table.Row operations"
returns: "table"
hosts: ["desktop"]
notes: false
examples: 1
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.RemoveRowsWithErrors

```m
Table.RemoveRowsWithErrors(table as table, optional columns as nullable list) as table
```

Returns a table with the rows removed from the input table that contain an error in at least one of the cells. If a columns list is specified, then only the cells in the specified columns are inspected for errors.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |
| `columns` | `nullable list` | yes |

**Executed examples (1):** [examples/table-row-operations/table-removerowswitherrors.md](../../examples/table-row-operations/table-removerowswitherrors.md)

## Examples (engine metadata — not verified here)

Remove error value from first row.

```m
Table.RemoveRowsWithErrors(
    Table.FromRecords({
        [Column1 = ...],
        [Column1 = 2],
        [Column1 = 3]
    })
)
```

Stated result:

```m
Table.FromRecords({
    [Column1 = 2],
    [Column1 = 3]
})
```
