---
name: "Table.DemoteHeaders"
category: "Table.Column operations"
returns: "table"
hosts: ["desktop"]
notes: false
examples: 0
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.DemoteHeaders

```m
Table.DemoteHeaders(table as table) as table
```

Demotes the column headers (i.e. column names) to the first row of values. The default column names are "Column1", "Column2" and so on.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |

## Examples (engine metadata — not verified here)

Demote the first row of values in the table.

```m
Table.DemoteHeaders(
    Table.FromRecords({
        [CustomerID = 1, Name = "Bob", Phone = "123-4567"],
        [CustomerID = 2, Name = "Jim", Phone = "987-6543"]
    })
)
```

Stated result:

```m
Table.FromRecords({
    [Column1 = "CustomerID", Column2 = "Name", Column3 = "Phone"],
    [Column1 = 1, Column2 = "Bob", Column3 = "123-4567"],
    [Column1 = 2, Column2 = "Jim", Column3 = "987-6543"]
})
```
