---
name: "Table.CombineColumns"
category: "Table.Transformation"
returns: "table"
hosts: ["desktop"]
notes: false
examples: 0
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.CombineColumns

```m
Table.CombineColumns(table as table, sourceColumns as list, combiner as function, column as text) as table
```

Combines the specified columns into a new column using the specified combiner function.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |
| `sourceColumns` | `list` | no |
| `combiner` | `function` | no |
| `column` | `text` | no |

## Examples (engine metadata — not verified here)

Combine the last and first names into a new column, separated by a comma.

```m
Table.CombineColumns(
    Table.FromRecords({[FirstName = "Bob", LastName = "Smith"]}),
    {"LastName", "FirstName"},
    Combiner.CombineTextByDelimiter(",", QuoteStyle.None),
    "FullName"
)
```

Stated result:

```m
Table.FromRecords({[FullName = "Smith,Bob"]})
```
