---
name: "Table.ColumnCount"
category: "Table.Information"
returns: "number"
hosts: ["desktop"]
notes: false
examples: 1
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.ColumnCount

```m
Table.ColumnCount(table as table) as number
```

Returns the number of columns in the table `table`.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |

**Executed examples (1):** [examples/table-information/table-columncount.md](../../examples/table-information/table-columncount.md)

## Examples (engine metadata — not verified here)

Find the number of columns in the table.

```m
Table.ColumnCount(
    Table.FromRecords({
        [CustomerID = 1, Name = "Bob", Phone = "123-4567"],
        [CustomerID = 2, Name = "Jim", Phone = "987-6543"],
        [CustomerID = 3, Name = "Paul", Phone = "543-7890"]
    })
)
```

Stated result:

```m
3
```
