---
name: "Table.Range"
category: "Table.Row operations"
returns: "table"
hosts: ["desktop"]
notes: false
examples: 1
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.Range

```m
Table.Range(table as table, offset as number, optional count as nullable number) as table
```

Returns the rows from the `table` starting at the specified `offset`. An optional parameter, `count`, specifies how many rows to return. By default, all the rows after the offset are returned.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |
| `offset` | `number` | no |
| `count` | `nullable number` | yes |

**Executed examples (1):** [examples/table-row-operations/table-range.md](../../examples/table-row-operations/table-range.md)

## Examples (engine metadata — not verified here)

Return all the rows starting at offset 1 in the table.

```m
Table.Range(
    Table.FromRecords({
        [CustomerID = 1, Name = "Bob", Phone = "123-4567"],
        [CustomerID = 2, Name = "Jim", Phone = "987-6543"],
        [CustomerID = 3, Name = "Paul", Phone = "543-7890"],
        [CustomerID = 4, Name = "Ringo", Phone = "232-1550"]
    }),
    1
)
```

Stated result:

```m
Table.FromRecords({
    [CustomerID = 2, Name = "Jim", Phone = "987-6543"],
    [CustomerID = 3, Name = "Paul", Phone = "543-7890"],
    [CustomerID = 4, Name = "Ringo", Phone = "232-1550"]
})
```

Return one row starting at offset 1 in the table.

```m
Table.Range(
    Table.FromRecords({
        [CustomerID = 1, Name = "Bob", Phone = "123-4567"],
        [CustomerID = 2, Name = "Jim", Phone = "987-6543"],
        [CustomerID = 3, Name = "Paul", Phone = "543-7890"],
        [CustomerID = 4, Name = "Ringo", Phone = "232-1550"]
    }),
    1,
    1
)
```

Stated result:

```m
Table.FromRecords({[CustomerID = 2, Name = "Jim", Phone = "987-6543"]})
```
