---
name: "Table.Repeat"
category: "Table.Row operations"
returns: "table"
hosts: ["desktop"]
notes: false
examples: 1
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.Repeat

```m
Table.Repeat(table as table, count as number) as table
```

Returns a table with the rows from the input `table` repeated the specified `count` times.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |
| `count` | `number` | no |

**Executed examples (1):** [examples/table-row-operations/table-repeat.md](../../examples/table-row-operations/table-repeat.md)

## Examples (engine metadata — not verified here)

Repeat the rows in the table two times.

```m
Table.Repeat(
    Table.FromRecords({
        [a = 1, b = "hello"],
        [a = 3, b = "world"]
    }),
    2
)
```

Stated result:

```m
Table.FromRecords({
    [a = 1, b = "hello"],
    [a = 3, b = "world"],
    [a = 1, b = "hello"],
    [a = 3, b = "world"]
})
```
