---
name: "Table.ContainsAll"
category: "Table.Membership"
returns: "logical"
hosts: ["desktop"]
notes: false
examples: 1
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.ContainsAll

```m
Table.ContainsAll(table as table, rows as list, optional equationCriteria as any) as logical
```

Indicates whether all the specified records in the list of records `rows`, appear as rows in the `table`.
An optional parameter `equationCriteria` may be specified to control comparison between the rows of the table.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |
| `rows` | `list` | no |
| `equationCriteria` | `any` | yes |

**Executed examples (1):** [examples/table-membership/table-containsall.md](../../examples/table-membership/table-containsall.md)

## Examples (engine metadata — not verified here)

Determine if the table contains all the rows, comparing only the column [CustomerID].

```m
Table.ContainsAll(
    Table.FromRecords({
        [CustomerID = 1, Name = "Bob", Phone = "123-4567"],
        [CustomerID = 2, Name = "Jim", Phone = "987-6543"],
        [CustomerID = 3, Name = "Paul", Phone = "543-7890"],
        [CustomerID = 4, Name = "Ringo", Phone = "232-1550"]
    }),
    {
        [CustomerID = 1, Name = "Bill"],
        [CustomerID = 2, Name = "Fred"]
    },
    "CustomerID"
)
```

Stated result:

```m
true
```

Determine if the table contains all the rows.

```m
Table.ContainsAll(
    Table.FromRecords({
        [CustomerID = 1, Name = "Bob", Phone = "123-4567"],
        [CustomerID = 2, Name = "Jim", Phone = "987-6543"],
        [CustomerID = 3, Name = "Paul", Phone = "543-7890"],
        [CustomerID = 4, Name = "Ringo", Phone = "232-1550"]
    }),
    {
        [CustomerID = 1, Name = "Bill"],
        [CustomerID = 2, Name = "Fred"]
    }
)
```

Stated result:

```m
false
```
