---
name: "Table.FindText"
category: "Table.Row operations"
returns: "table"
hosts: ["desktop"]
notes: false
examples: 0
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.FindText

```m
Table.FindText(table as table, text as text) as table
```

Returns the rows in the table `table` that contain the text `text`. If the text is not found, an empty table is returned.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |
| `text` | `text` | no |

## Examples (engine metadata — not verified here)

Find the rows in the table that contain "Bob".

```m
Table.FindText(
    Table.FromRecords({
        [CustomerID = 1, Name = "Bob", Phone = "123-4567"],
        [CustomerID = 2, Name = "Jim", Phone = "987-6543"],
        [CustomerID = 3, Name = "Paul", Phone = "543-7890"],
        [CustomerID = 4, Name = "Ringo", Phone = "232-1550"]
    }),
    "Bob"
)
```

Stated result:

```m
Table.FromRecords({[CustomerID = 1, Name = "Bob", Phone = "123-4567"]})
```
