---
name: "Table.ToRecords"
category: "Table.Conversions"
returns: "list"
hosts: ["desktop"]
notes: false
examples: 0
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.ToRecords

```m
Table.ToRecords(table as table) as list
```

Converts a table, `table`, to a list of records.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |

## Examples (engine metadata — not verified here)

Convert the table to a list of records.

```m
Table.ToRecords(
    Table.FromRows(
        {
            {1, "Bob", "123-4567"},
            {2, "Jim", "987-6543"},
            {3, "Paul", "543-7890"}
        },
        {"CustomerID", "Name", "Phone"}
    )
)
```

Stated result:

```m
{
    [CustomerID = 1, Name = "Bob", Phone = "123-4567"],
    [CustomerID = 2, Name = "Jim", Phone = "987-6543"],
    [CustomerID = 3, Name = "Paul", Phone = "543-7890"]
}
```
