---
name: "Table.TransformRows"
category: "Table.Transformation"
returns: "list"
hosts: ["desktop"]
notes: false
examples: 0
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.TransformRows

```m
Table.TransformRows(table as table, transform as function) as list
```

Creates a `list` by applying the `transform` operation to each row in `table`.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |
| `transform` | `function` | no |

## Examples (engine metadata — not verified here)

Transform the rows of a table into a list of numbers.

```m
Table.TransformRows(
    Table.FromRecords({
        [a = 1],
        [a = 2],
        [a = 3],
        [a = 4],
        [a = 5]
    }),
    each [a]
)
```

Stated result:

```m
{1, 2, 3, 4, 5}
```

Transform the rows of a numeric table into textual records.

```m
Table.TransformRows(
    Table.FromRecords({
        [a = 1],
        [a = 2],
        [a = 3],
        [a = 4],
        [a = 5]
    }),
    (row) as record => [B = Number.ToText(row[a])]
)
```

Stated result:

```m
{
    [B = "1"],
    [B = "2"],
    [B = "3"],
    [B = "4"],
    [B = "5"]
}
```
