---
name: "Table.ReplaceValue"
category: "Table.Transformation"
returns: "table"
hosts: ["desktop"]
notes: false
examples: 0
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.ReplaceValue

```m
Table.ReplaceValue(table as table, oldValue as any, newValue as any, replacer as function, columnsToSearch as list) as table
```

Replaces a value with a new value in the specified columns of a table.

- `table`: The table to search.

- `oldValue`: The value to be replaced.

- `newValue`: The replacement value.

- `replacer`: The replacer function to use. The function can be either `Replacer.ReplaceText` to replace the original text with new text, `Replacer.ReplaceValue` to replace the original value with a new value, or a custom replacer.

- `columnsToSearch`: A list containing the specific column or columns in the table to search for the value to replace.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |
| `oldValue` | `any` | no |
| `newValue` | `any` | no |
| `replacer` | `function` | no |
| `columnsToSearch` | `list` | no |

## Examples (engine metadata — not verified here)

Replace the text "goodbye" with "world" in column B, matching only the entire value.

```m
Table.ReplaceValue(
    Table.FromRecords({
        [A = 1, B = "hello"],
        [A = 2, B = "goodbye"],
        [A = 3, B = "goodbyes"]
    }),
    "goodbye",
    "world",
    Replacer.ReplaceValue,
    {"B"}
)
```

Stated result:

```m
Table.FromRecords({
    [A = 1, B = "hello"],
    [A = 2, B = "world"],
    [A = 3, B = "goodbyes"]
})
```

Replace the text "ur" with "or" in column B, matching any part of the value.

```m
Table.ReplaceValue(
    Table.FromRecords({
        [A = 1, B = "hello"],
        [A = 2, B = "wurld"]
    }),
    "ur",
    "or",
    Replacer.ReplaceText,
    {"B"}
)
```

Stated result:

```m
Table.FromRecords({
    [A = 1, B = "hello"],
    [A = 2, B = "world"]
})
```

Anonymize the names of US employees.

```m
Table.ReplaceValue(
    Table.FromRecords({
        [Name = "Cindy", Country = "US"],
        [Name = "Bob", Country = "CA"]
    }),
    each if [Country] = "US" then [Name] else false,
    each Text.Repeat("*", Text.Length([Name])),
    Replacer.ReplaceValue,
    {"Name"}
)
```

Stated result:

```m
Table.FromRecords({
    [Name = "*****", Country = "US"],
    [Name = "Bob", Country = "CA"]
})
```

Anonymize all columns of US employees.

```m
Table.ReplaceValue(
    Table.FromRecords({
        [Name = "Cindy", Country = "US"],
        [Name = "Bob", Country = "CA"]
    }),
    each [Country] = "US",
    "?",
    (currentValue, isUS, replacementValue) =>
        if isUS then
            Text.Repeat(replacementValue, Text.Length(currentValue))
        else
            currentValue,
    {"Name", "Country"}
)
```

Stated result:

```m
Table.FromRecords({
    [Name = "?????", Country = "??"],
    [Name = "Bob", Country = "CA"]
})
```
