---
name: "Table.PromoteHeaders"
category: "Table.Column operations"
returns: "table"
hosts: ["desktop"]
notes: false
examples: 1
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.PromoteHeaders

```m
Table.PromoteHeaders(table as table, optional options as nullable record) as table
```

Promotes the first row of values as the new column headers (i.e. column names). By default, only text or number values are promoted to headers. Valid options:

- `PromoteAllScalars`: If set to `true`, all the scalar values in the first row are promoted to headers using the `Culture`, if specified (or current document locale).
For values that cannot be converted to text, a default column name will be used.

- `Culture`: A culture name specifying the culture for the data.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |
| `options` | `nullable record` | yes |

**Executed examples (1):** [examples/table-column-operations/table-promoteheaders.md](../../examples/table-column-operations/table-promoteheaders.md)

## Examples (engine metadata — not verified here)

Promote the first row of values in the table.

```m
Table.PromoteHeaders(
    Table.FromRecords({
        [Column1 = "CustomerID", Column2 = "Name", Column3 = #date(1980, 1, 1)],
        [Column1 = 1, Column2 = "Bob", Column3 = #date(1980, 1, 1)]
    })
)
```

Stated result:

```m
Table.FromRecords({[CustomerID = 1, Name = "Bob", Column3 = #date(1980, 1, 1)]})
```

Promote all the scalars in the first row of the table to headers.

```m
Table.PromoteHeaders(
    Table.FromRecords({
        [Rank = 1, Name = "Name", Date = #date(1980, 1, 1)],
        [Rank = 1, Name = "Bob", Date = #date(1980, 1, 1)]}
    ),
    [PromoteAllScalars = true, Culture = "en-US"]
)
```

Stated result:

```m
Table.FromRecords({[1 = 1, Name = "Bob", #"1/1/1980" = #date(1980, 1, 1)]})
```
