---
name: "Table.ExpandListColumn"
category: "Table.Transformation"
returns: "table"
hosts: ["desktop"]
notes: false
examples: 1
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.ExpandListColumn

```m
Table.ExpandListColumn(table as table, column as text) as table
```

Given a `table` where `column` contains a list of values, splits the list into a row for each value. Values in the other columns are duplicated in each new row created. This function can also expand nested tables by treating them as lists of records.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |
| `column` | `text` | no |

**Executed examples (1):** [examples/table-transformation/table-expandlistcolumn.md](../../examples/table-transformation/table-expandlistcolumn.md)

## Examples (engine metadata — not verified here)

Split the list column [Name].

```m
Table.ExpandListColumn(
    Table.FromRecords({[Name = {"Bob", "Jim", "Paul"}, Discount = .15]}),
    "Name"
)
```

Stated result:

```m
Table.FromRecords({
    [Name = "Bob", Discount = 0.15],
    [Name = "Jim", Discount = 0.15],
    [Name = "Paul", Discount = 0.15]
})
```

Split the nested table column [Components].

```m
Table.ExpandListColumn(
    #table(
        {"Part", "Components"},
        {
            {"Tool", #table({"Name", "Quantity"}, {{"Thingamajig", 2}, {"Widget", 3}})}
        }
    ),
    "Components"
)
```

Stated result:

```m
Table.FromRecords({
    [Part = "Tool", Components = [Name = "Thingamajig", Quantity = 2]],
    [Part = "Tool", Components = [Name = "Widget", Quantity = 3]]
})
```
