---
name: "Table.DuplicateColumn"
category: "Table.Column operations"
returns: "table"
hosts: ["desktop"]
notes: false
examples: 1
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.DuplicateColumn

```m
Table.DuplicateColumn(table as table, columnName as text, newColumnName as text, optional columnType as nullable type) as table
```

Duplicate the column named `columnName` to the table `table`. The values and type for the column `newColumnName` are copied from column `columnName`.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |
| `columnName` | `text` | no |
| `newColumnName` | `text` | no |
| `columnType` | `nullable type` | yes |

**Executed examples (1):** [examples/table-column-operations/table-duplicatecolumn.md](../../examples/table-column-operations/table-duplicatecolumn.md)

## Examples (engine metadata — not verified here)

Duplicate the column "a" to a column named "copied column" in the table `({[a = 1, b = 2], [a = 3, b = 4]})`.

```m
Table.DuplicateColumn(
    Table.FromRecords({
        [a = 1, b = 2],
        [a = 3, b = 4]
    }),
    "a",
    "copied column"
)
```

Stated result:

```m
Table.FromRecords({
    [a = 1, b = 2, #"copied column" = 1],
    [a = 3, b = 4, #"copied column" = 3]
})
```
