---
name: "Table.PositionOf"
category: "Table.Membership"
returns: "any"
hosts: ["desktop"]
notes: false
examples: 1
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.PositionOf

```m
Table.PositionOf(table as table, row as record, optional occurrence as any, optional equationCriteria as any) as any
```

Returns the row position of the first occurrence of the `row` in the `table` specified. Returns -1 if no occurrence is found.

- `table`: The input table.

- `row`: The row in the table to find the position of.

- `occurrence`: *(Optional)* Specifies which occurrences of the row to return.

- `equationCriteria`: *(Optional)* Controls the comparison between the table rows.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |
| `row` | `record` | no |
| `occurrence` | `any` | yes |
| `equationCriteria` | `any` | yes |

**Executed examples (1):** [examples/table-membership/table-positionof.md](../../examples/table-membership/table-positionof.md)

## Examples (engine metadata — not verified here)

Find the position of the first occurrence of [a = 2, b = 4] in the table `({[a = 2, b = 4], [a = 6, b = 8], [a = 2, b = 4], [a = 1, b = 4]})`.

```m
Table.PositionOf(
    Table.FromRecords({
        [a = 2, b = 4],
        [a = 1, b = 4],
        [a = 2, b = 4],
        [a = 1, b = 4]
    }),
    [a = 2, b = 4]
)
```

Stated result:

```m
0
```

Find the position of the second occurrence of [a = 2, b = 4] in the table `({[a = 2, b = 4], [a = 6, b = 8], [a = 2, b = 4], [a = 1, b = 4]})`.

```m
Table.PositionOf(
    Table.FromRecords({
        [a = 2, b = 4],
        [a = 1, b = 4],
        [a = 2, b = 4],
        [a = 1, b = 4]
    }),
    [a = 2, b = 4],
    1
)
```

Stated result:

```m
2
```

Find the position of all the occurrences of [a = 2, b = 4] in the table `({[a = 2, b = 4], [a = 6, b = 8], [a = 2, b = 4], [a = 1, b = 4]})`.

```m
Table.PositionOf(
    Table.FromRecords({
        [a = 2, b = 4],
        [a = 1, b = 4],
        [a = 2, b = 4],
        [a = 1, b = 4]
    }),
    [a = 2, b = 4],
    Occurrence.All
)
```

Stated result:

```m
{0, 2}
```
