---
name: "Table.ToColumns"
category: "Table.Conversions"
returns: "list"
hosts: ["desktop"]
notes: false
examples: 0
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.ToColumns

```m
Table.ToColumns(table as table) as list
```

Creates a list of nested lists from the table, `table`. Each list item is an inner list that contains the column values.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |

## Examples (engine metadata — not verified here)

Create a list of the column values from the table.

```m
Table.ToColumns(
    Table.FromRecords({
        [CustomerID = 1, Name = "Bob", Phone = "123-4567"],
        [CustomerID = 2, Name = "Jim", Phone = "987-6543"]
    })
)
```

Stated result:

```m
{{1, 2}, {"Bob", "Jim"}, {"123-4567", "987-6543"}}
```
