---
name: "Table.Column"
category: "Table.Column operations"
returns: "list"
hosts: ["desktop"]
notes: false
examples: 0
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.Column

```m
Table.Column(table as table, column as text) as list
```

Returns the column of data specified by `column` from the table `table` as a list.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |
| `column` | `text` | no |

## Examples (engine metadata — not verified here)

Returns the values from the [Name] column in the table.

```m
Table.Column(
    Table.FromRecords({
        [CustomerID = 1, Name = "Bob", Phone = "123-4567"],
        [CustomerID = 2, Name = "Jim", Phone = "987-6543"],
        [CustomerID = 3, Name = "Paul", Phone = "543-7890"],
        [CustomerID = 4, Name = "Ringo", Phone = "232-1550"]
    }),
    "Name"
)
```

Stated result:

```m
{"Bob", "Jim", "Paul", "Ringo"}
```
