---
name: "Table.ReplaceKeys"
category: "Table.Transformation"
returns: "table"
hosts: ["desktop"]
notes: false
examples: 0
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.ReplaceKeys

```m
Table.ReplaceKeys(table as table, keys as list) as table
```

Replaces the keys of the specified table.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |
| `keys` | `list` | no |

## Examples (engine metadata — not verified here)

Replace the existing keys of a table.

```m
let
    table = Table.FromRecords({
        [Id = 1, Name = "Hello There"],
        [Id = 2, Name = "Good Bye"]
    }),
    tableWithKeys = Table.AddKey(table, {"Id"}, true),
    resultTable = Table.ReplaceKeys(tableWithKeys, {[Columns = {"Id"}, Primary = false]})
in
    resultTable
```

Stated result:

```m
Table.FromRecords({
    [Id = 1, Name = "Hello There"],
    [Id = 2, Name = "Good Bye"]
})
```
