---
name: "Table.FromValue"
category: "Table.Table construction"
returns: "table"
hosts: ["desktop"]
notes: false
examples: 0
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.FromValue

```m
Table.FromValue(value as any, optional options as nullable record) as table
```

Creates a table with a column containing the provided value or list of values, `value`. An optional record parameter, `options`, may be specified to control the following options:

- `DefaultColumnName`: The column name used when constructing a table from a list or scalar value.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `value` | `any` | no |
| `options` | `nullable record` | yes |

## Examples (engine metadata — not verified here)

Create a table from the value 1.

```m
Table.FromValue(1)
```

Stated result:

```m
Table.FromRecords({[Value = 1]})
```

Create a table from the list.

```m
Table.FromValue({1, "Bob", "123-4567"})
```

Stated result:

```m
Table.FromRecords({
    [Value = 1],
    [Value = "Bob"],
    [Value = "123-4567"]
})
```

Create a table from the value 1, with a custom column name.

```m
Table.FromValue(1, [DefaultColumnName = "MyValue"])
```

Stated result:

```m
Table.FromRecords({[MyValue = 1]})
```
