---
name: "Table.RemoveColumns"
category: "Table.Column operations"
returns: "table"
hosts: ["desktop"]
notes: false
examples: 1
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.RemoveColumns

```m
Table.RemoveColumns(table as table, columns as any, optional missingField as nullable number) as table
```

Removes the specified `columns` from the `table` provided.
If the specified column doesn't exist, an error is raised unless the optional parameter `missingField` specifies an alternative behavior (for example, `MissingField.UseNull` or `MissingField.Ignore`).

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |
| `columns` | `any` | no |
| `missingField` | `nullable number` | yes |

**Executed examples (1):** [examples/table-column-operations/table-removecolumns.md](../../examples/table-column-operations/table-removecolumns.md)

## Examples (engine metadata — not verified here)

Remove column [Phone] from the table.

```m
Table.RemoveColumns(
    Table.FromRecords({[CustomerID = 1, Name = "Bob", Phone = "123-4567"]}),
    "Phone"
)
```

Stated result:

```m
Table.FromRecords({[CustomerID = 1, Name = "Bob"]})
```

Try to remove a non-existent column from the table.

```m
Table.RemoveColumns(
    Table.FromRecords({[CustomerID = 1, Name = "Bob", Phone = "123-4567"]}),
    "Address"
)
```

Stated result:

```m
[Expression.Error] The column 'Address' of the table wasn't found.
```
