---
name: "Table.SplitAt"
category: "Table.Row operations"
returns: "list"
hosts: ["desktop"]
notes: false
examples: 0
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.SplitAt

```m
Table.SplitAt(table as table, count as number) as list
```

Returns a list containing two tables: a table with the first N rows of `table` (as specified by `count`) and a table containing the remaining rows of `table`.

If the tables of the resulting list are enumerated exactly once and in order, the function will enumerate `table` only once.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |
| `count` | `number` | no |

## Examples (engine metadata — not verified here)

Return the first two rows of the table and the remaining rows of the table.

```m
Table.SplitAt(#table({"a", "b", "c"}, {{1, 2, 3}, {4, 5, 6}, {7, 8, 9}}), 2)
```

Stated result:

```m
{
    #table({"a", "b", "c"}, {{1, 2, 3}, {4, 5, 6}}),
    #table({"a", "b", "c"}, {{7, 8, 9}})
}
```
