---
name: "Table.Split"
category: "Table.Transformation"
returns: "list"
hosts: ["desktop"]
notes: false
examples: 0
source: "#shared \u2014 desktop 2.157.879.0"
---

<!-- Generated by scripts/sync_shared.py. Do not edit: write in notes/ instead. -->

# Table.Split

```m
Table.Split(table as table, pageSize as number) as list
```

Splits `table` into a list of tables where the first element of the list is a table containing the first `pageSize` rows from
the source table, the next element of the list is a table containing the next `pageSize` rows from the source table, and so on.

## Parameters

| Name | Type | Optional |
|---|---|---|
| `table` | `table` | no |
| `pageSize` | `number` | no |

## Examples (engine metadata — not verified here)

Split a table of five records into tables with two records each.

```m
let
    Customers = Table.FromRecords({
        [CustomerID = 1, Name = "Bob", Phone = "123-4567"],
        [CustomerID = 2, Name = "Jim", Phone = "987-6543"],
        [CustomerID = 3, Name = "Paul", Phone = "543-7890"],
        [CustomerID = 4, Name = "Cristina", Phone = "232-1550"],
        [CustomerID = 5, Name = "Anita", Phone = "530-1459"]
    })
in
    Table.Split(Customers, 2)
```

Stated result:

```m
{
    Table.FromRecords({
        [CustomerID = 1, Name = "Bob", Phone = "123-4567"],
        [CustomerID = 2, Name = "Jim", Phone = "987-6543"]
    }),
    Table.FromRecords({
        [CustomerID = 3, Name = "Paul", Phone = "543-7890"],
        [CustomerID = 4, Name = "Cristina", Phone = "232-1550"]
    }),
    Table.FromRecords({
        [CustomerID = 5, Name = "Anita", Phone = "530-1459"]
    })
}
```
