#!/usr/bin/env python3
"""Build SharedExport.pbip: a one-table model whose partition IS export_shared.pq.

The query is embedded, not copied by hand, so the file that runs in Desktop is always the
one in skills/m-reference/scripts/. Rebuild after editing the query:

  python lab/shared-export/build_pbip.py --host desktop --host-version 2.157.879.0

Then open SharedExport.pbip in Power BI Desktop and run export_desktop.ps1, which refreshes
the table over the local Analysis Services port and writes exports/<host>-<version>.json.
"""
import argparse
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
QUERY = os.path.join(ROOT, "skills", "m-reference", "scripts", "export_shared.pq")
NAME = "SharedExport"


def write(rel, text):
    path = os.path.join(HERE, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\r\n") as f:
        f.write(text)


def json_text(obj):
    return json.dumps(obj, indent=2) + "\n"


def partition_source(host, host_version):
    with open(QUERY, encoding="utf-8") as f:
        query = f.read()
    query, n_host = re.subn(r'^(\s*Host = )"[^"]*",', rf'\1"{host}",', query, flags=re.M)
    query, n_ver = re.subn(r'^(\s*HostVersion = )"[^"]*",', rf'\1"{host_version}",', query,
                           flags=re.M)
    if n_host != 1 or n_ver != 1:
        raise SystemExit("export_shared.pq no longer has exactly one Host and one HostVersion line")
    # TMDL ends a multi-line expression at the first line indented less than it, so every
    # line gets the same 4-tab prefix and blank lines are dropped.
    lines = [line for line in query.splitlines() if line.strip()]
    return "\n".join("\t\t\t\t" + line for line in lines)


def build(host, host_version):
    write(f"{NAME}.pbip", json_text({
        "$schema": "https://developer.microsoft.com/json-schemas/fabric/pbip/pbipProperties/1.0.0/schema.json",
        "version": "1.0",
        "artifacts": [{"report": {"path": f"{NAME}.Report"}}],
        "settings": {"enableAutoRecovery": False},
    }))
    sm = f"{NAME}.SemanticModel"
    write(f"{sm}/definition.pbism", json_text({
        "$schema": "https://developer.microsoft.com/json-schemas/fabric/item/semanticModel/definitionProperties/1.0.0/schema.json",
        "version": "4.2", "settings": {},
    }))
    write(f"{sm}/.platform", json_text({
        "$schema": "https://developer.microsoft.com/json-schemas/fabric/gitIntegration/platformProperties/2.0.0/schema.json",
        "metadata": {"type": "SemanticModel", "displayName": NAME},
        "config": {"version": "2.0", "logicalId": "5a4ed000-0000-4000-8000-000000000001"},
    }))
    write(f"{sm}/definition/database.tmdl", "database\n\tcompatibilityLevel: 1606\n")
    write(f"{sm}/definition/model.tmdl",
          "model Model\n"
          "\tculture: en-US\n"
          "\tdefaultPowerBIDataSourceVersion: powerBI_V3\n"
          "\tsourceQueryCulture: en-US\n"
          "\tdataAccessOptions\n"
          "\t\tlegacyRedirects\n"
          "\t\treturnErrorValuesAsNull\n"
          "\n"
          f'annotation PBI_QueryOrder = ["{NAME}"]\n'
          "\n"
          f"ref table {NAME}\n")
    write(f"{sm}/definition/tables/{NAME}.tmdl",
          "/// Generated by lab/shared-export/build_pbip.py from export_shared.pq. Do not edit.\n"
          f"table {NAME}\n"
          "\tlineageTag: 5a4ed000-0000-4000-8000-000000000101\n"
          "\n"
          "\tcolumn part\n"
          "\t\tdataType: int64\n"
          "\t\tlineageTag: 5a4ed000-0000-4000-8000-000000000102\n"
          "\t\tsummarizeBy: none\n"
          "\t\tsourceColumn: part\n"
          "\n"
          "\tcolumn json\n"
          "\t\tdataType: string\n"
          "\t\tlineageTag: 5a4ed000-0000-4000-8000-000000000103\n"
          "\t\tsummarizeBy: none\n"
          "\t\tsourceColumn: json\n"
          "\n"
          f"\tpartition {NAME} = m\n"
          "\t\tmode: import\n"
          "\t\tsource =\n"
          f"{partition_source(host, host_version)}\n"
          "\n"
          "\tannotation PBI_ResultType = Table\n")
    rp = f"{NAME}.Report"
    write(f"{rp}/definition.pbir", json_text({
        "$schema": "https://developer.microsoft.com/json-schemas/fabric/item/report/definitionProperties/2.0.0/schema.json",
        "version": "4.0",
        "datasetReference": {"byPath": {"path": f"../{sm}"}},
    }))
    write(f"{rp}/.platform", json_text({
        "$schema": "https://developer.microsoft.com/json-schemas/fabric/gitIntegration/platformProperties/2.0.0/schema.json",
        "metadata": {"type": "Report", "displayName": NAME},
        "config": {"version": "2.0", "logicalId": "5a4ed000-0000-4000-8000-000000000002"},
    }))
    write(f"{rp}/definition/version.json", json_text({
        "$schema": "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/versionMetadata/1.0.0/schema.json",
        "version": "2.0.0",
    }))
    write(f"{rp}/definition/report.json", json_text({
        "$schema": "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/report/3.3.0/schema.json",
        "themeCollection": {"baseTheme": {
            "name": "CY25SU11",
            "reportVersionAtImport": {"visual": "2.10.0", "report": "3.4.0", "page": "2.3.1"},
            "type": "SharedResources"}},
        "resourcePackages": [{"name": "SharedResources", "type": "SharedResources", "items": [
            {"name": "CY25SU11", "path": "BaseThemes/CY25SU11.json", "type": "BaseTheme"}]}],
    }))
    write(f"{rp}/definition/pages/pages.json", json_text({
        "$schema": "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/pagesMetadata/1.0.0/schema.json",
        "pageOrder": ["export"], "activePageName": "export",
    }))
    write(f"{rp}/definition/pages/export/page.json", json_text({
        "$schema": "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/2.0.0/schema.json",
        "name": "export", "displayName": "Export", "displayOption": "FitToPage",
        "height": 720, "width": 1280,
    }))


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--host", default="desktop")
    parser.add_argument("--host-version", default="")
    args = parser.parse_args()
    build(args.host, args.host_version)
    print(f"Built {os.path.join(HERE, NAME + '.pbip')} (host={args.host}, "
          f"version={args.host_version or 'unset'})")


if __name__ == "__main__":
    main()
