/// Generated by lab/review/build_review.py from the example pages. Do not edit.
table DateTime
	lineageTag: b0fb73c0-13c0-54dd-baf4-ff461e353924

	column seq
		dataType: int64
		lineageTag: f0c944f8-0d8a-59a0-b52d-e649aa4a3ad3
		summarizeBy: none
		sourceColumn: seq

	column Function
		dataType: string
		lineageTag: 4b87b6f2-fdab-5c40-a0a8-6f5a8ba56be3
		summarizeBy: none
		sourceColumn: Function

	column Block
		dataType: int64
		lineageTag: 76234084-6b92-5e71-bd68-1f29dd7d9f48
		summarizeBy: none
		sourceColumn: Block

	column Code
		dataType: string
		lineageTag: 1c8d438d-bfd5-5e62-b444-8be4e4d34f8d
		summarizeBy: none
		sourceColumn: Code

	column Recorded
		dataType: string
		lineageTag: 99a08e6d-855a-5c2c-b9fc-3757ed96023b
		summarizeBy: none
		sourceColumn: Recorded

	column Live
		dataType: string
		lineageTag: fd0cd7d2-54ce-59b0-90c6-5d8b31c14e3b
		summarizeBy: none
		sourceColumn: Live

	column Match
		dataType: string
		lineageTag: c2385cd4-c47b-5dbf-9840-d8c585f6ef35
		summarizeBy: none
		sourceColumn: Match

	measure Examples = COUNTROWS('DateTime')
		formatString: 0
		lineageTag: 9cce1e6c-be13-5a74-9993-13eb61275876

	partition DateTime = m
		mode: import
		source =
				let
				    Live = 
				        // runner.pq - evaluates every ```m block of the skills in the engine and renders each result
				        // as M literal text, so a page can quote what the engine returned instead of what we expect.
				        //
				        // run_examples.py replaces the Cases line with the blocks it collected and builds a PBIP
				        // whose only partition is this query. It also replaces the Allowed line with the names
				        // m_blocks.allowed_names lets a block use, and each case is evaluated with Expression.Evaluate
				        // over those members of #shared only: no data sources, no connectors, no other queries, no
				        // Expression.Evaluate - even for a name m_blocks.unsafe_calls could not see.
				        let
				            Cases = {{"0", "DateTime.AddZone(null, 7, 30)"}, {"1", "DateTime.AddZone(#datetime(2010, 12, 31, 11, 56, 2), -5)"}, {"2", "DateTime.AddZone(#datetime(2200, 6, 15, 23, 59, 59), -3, -30)"}, {"3", "DateTime.Date(null)"}, {"4", "DateTime.Date(#datetime(1990, 1, 1, 23, 59, 59))"}, {"5", "DateTime.Date(#datetimezone(2200, 12, 31, 0, 0, 0, 8, 0))"}, {"6", "DateTime.From(null)"}, {"7", "DateTime.From(""12/31/1990 11:59:59 PM"", ""en-US"")"}, {"8", "DateTime.From(#time(6, 45, 12))"}, {"9", "DateTime.FromText(null)"}, {"10", "DateTime.FromText(""01/02/2010 03:04:05"", ""en-GB"")"}, {"11", "DateTime.FromText(""30 Dez 2010 02:04:50.369730"", [Format = ""dd MMM yyyy HH:mm:ss.ffffff"", Culture = ""de-DE""])"}, {"12", "DateTime.IsInCurrentHour(#datetime(1990, 1, 1, 0, 0, 0))"}, {"13", "DateTime.IsInCurrentHour(#datetimezone(2200, 1, 1, 0, 0, 0, 0, 0))"}, {"14", "DateTime.IsInCurrentHour(null)"}, {"15", "DateTime.IsInCurrentMinute(null)"}, {"16", "DateTime.IsInCurrentMinute(#datetime(1990, 12, 31, 23, 59, 0))"}, {"17", "DateTime.IsInCurrentMinute(#datetimezone(2200, 1, 1, 0, 0, 0, 0, 0))"}, {"18", "DateTime.IsInCurrentSecond(null)"}, {"19", "DateTime.IsInCurrentSecond(#datetime(1990, 1, 1, 0, 0, 0))"}, {"20", "DateTime.IsInCurrentSecond(#datetimezone(2200, 1, 1, 0, 0, 0, 0, 0))"}, {"21", "DateTime.IsInNextHour(#datetime(2200, 1, 1, 0, 0, 0))"}, {"22", "DateTime.IsInNextHour(#datetimezone(1990, 1, 1, 0, 0, 0, 0, 0))"}, {"23", "DateTime.IsInNextHour(null)"}, {"24", "DateTime.IsInNextMinute(null)"}, {"25", "DateTime.IsInNextMinute(#datetime(1990, 1, 1, 0, 0, 0))"}, {"26", "DateTime.IsInNextMinute(#datetimezone(2200, 1, 1, 0, 0, 0, 5, 0))"}, {"27", "DateTime.IsInNextNHours(null, 3)"}, {"28", "DateTime.IsInNextNHours(#datetime(1990, 1, 1, 0, 0, 0), 3)"}, {"29", "DateTime.IsInNextNHours(#datetime(2200, 1, 1, 0, 0, 0), 2000000)"}, {"30", "DateTime.IsInNextNMinutes(null, 5)"}, {"31", "DateTime.IsInNextNMinutes(#datetime(1990, 12, 31, 23, 59, 0), 5)"}, {"32", "DateTime.IsInNextNMinutes(#datetimezone(2200, 1, 1, 0, 0, 0, 0, 0), 60)"}, {"33", "DateTime.IsInNextNSeconds(null, 10)"}, {"34", "DateTime.IsInNextNSeconds(#datetime(1990, 1, 1, 0, 0, 0), 60)"}, {"35", "DateTime.IsInNextNSeconds(#datetimezone(2200, 1, 1, 0, 0, 0, 0, 0), 10000000000)"}, {"36", "DateTime.IsInNextSecond(null)"}, {"37", "DateTime.IsInNextSecond(#datetime(1990, 12, 31, 23, 59, 59))"}, {"38", "DateTime.IsInNextSecond(#datetimezone(2200, 1, 1, 0, 0, 0, 0, 0))"}, {"39", "DateTime.IsInPreviousHour(null)"}, {"40", "DateTime.IsInPreviousHour(#datetime(1990, 1, 1, 0, 0, 0))"}, {"41", "DateTime.IsInPreviousHour(#datetimezone(2200, 1, 1, 0, 0, 0, 0, 0))"}, {"42", "DateTime.IsInPreviousMinute(null)"}, {"43", "DateTime.IsInPreviousMinute(#datetime(1990, 1, 1, 0, 0, 0))"}, {"44", "DateTime.IsInPreviousMinute(#datetimezone(2200, 1, 1, 0, 0, 0, 0, 0))"}, {"45", "DateTime.IsInPreviousNHours(null, 2)"}, {"46", "DateTime.IsInPreviousNHours(#datetime(1990, 1, 1, 0, 0, 0), 2)"}, {"47", "DateTime.IsInPreviousNHours(#datetimezone(2200, 1, 1, 0, 0, 0, 0, 0), 2)"}, {"48", "DateTime.IsInPreviousNMinutes(#datetime(1990, 1, 1, 0, 0, 0), 5)"}, {"49", "DateTime.IsInPreviousNMinutes(#datetimezone(2200, 1, 1, 0, 0, 0, 0, 0), 5)"}, {"50", "DateTime.IsInPreviousNMinutes(null, 5)"}, {"51", "DateTime.IsInPreviousNSeconds(null, 10)"}, {"52", "DateTime.IsInPreviousNSeconds(#datetime(1990, 1, 1, 0, 0, 0), 60)"}, {"53", "DateTime.IsInPreviousNSeconds(#datetimezone(2200, 12, 31, 23, 59, 59, 0, 0), 60)"}, {"54", "DateTime.IsInPreviousSecond(#datetime(1990, 1, 1, 0, 0, 0))"}, {"55", "DateTime.IsInPreviousSecond(null)"}, {"56", "DateTime.IsInPreviousSecond(#datetimezone(2200, 1, 1, 0, 0, 0, 0, 0))"}, {"57", "DateTime.Time(#datetime(2200, 6, 15, 4, 5, 6))"}, {"58", "DateTime.Time(#date(1990, 1, 1))"}, {"59", "DateTime.Time(null)"}, {"60", "DateTime.ToRecord(#datetime(1990, 3, 15, 13, 45, 30))"}, {"61", "DateTime.ToRecord(null)"}, {"62", "DateTime.ToRecord(#datetime(2200, 12, 31, 23, 59, 59.5))"}, {"63", "DateTime.ToText(null)"}, {"64", "DateTime.ToText(#datetime(2010, 12, 30, 2, 4, 50.36973), ""dd MMM yyyy"", ""de-DE"")"}, {"65", "DateTime.ToText(#datetime(2010, 12, 31, 13, 30, 25), [Format = null, Culture = ""en-US""])"}},
				            Allowed = {"AccessControlEntry.ConditionContextType", "AccessControlEntry.Type", "AccessControlKind.Allow", "AccessControlKind.Deny", "AccessControlKind.Type", "Any.Type", "Binary.ApproximateLength", "Binary.Buffer", "Binary.Combine", "Binary.Compress", "Binary.Decompress", "Binary.From", "Binary.FromList", "Binary.FromText", "Binary.InferContentType", "Binary.Length", "Binary.Range", "Binary.Split", "Binary.ToList", "Binary.ToText", "Binary.Type", "Binary.View", "Binary.ViewError", "Binary.ViewFunction", "BinaryEncoding.Base64", "BinaryEncoding.Hex", "BinaryEncoding.Type", "BinaryFormat.7BitEncodedSignedInteger", "BinaryFormat.7BitEncodedUnsignedInteger", "BinaryFormat.Binary", "BinaryFormat.Byte", "BinaryFormat.ByteOrder", "BinaryFormat.Choice", "BinaryFormat.Decimal", "BinaryFormat.Double", "BinaryFormat.Group", "BinaryFormat.Length", "BinaryFormat.List", "BinaryFormat.Null", "BinaryFormat.Record", "BinaryFormat.SignedInteger16", "BinaryFormat.SignedInteger32", "BinaryFormat.SignedInteger64", "BinaryFormat.Single", "BinaryFormat.Text", "BinaryFormat.Transform", "BinaryFormat.UnsignedInteger16", "BinaryFormat.UnsignedInteger32", "BinaryFormat.UnsignedInteger64", "BinaryOccurrence.Optional", "BinaryOccurrence.Repeating", "BinaryOccurrence.Required", "BinaryOccurrence.Type", "BufferMode.Delayed", "BufferMode.Eager", "BufferMode.Type", "Byte.From", "Byte.Type", "ByteOrder.BigEndian", "ByteOrder.LittleEndian", "ByteOrder.Type", "Certificate.Type", "Character.FromNumber", "Character.ToNumber", "Character.Type", "Combiner.CombineTextByDelimiter", "Combiner.CombineTextByEachDelimiter", "Combiner.CombineTextByLengths", "Combiner.CombineTextByPositions", "Combiner.CombineTextByRanges", "Comparer.Equals", "Comparer.FromCulture", "Comparer.Ordinal", "Comparer.OrdinalIgnoreCase", "Compression.Brotli", "Compression.Deflate", "Compression.GZip", "Compression.LZ4", "Compression.None", "Compression.Snappy", "Compression.Type", "Compression.Zstandard", "Csv.Document", "CsvStyle.QuoteAfterDelimiter", "CsvStyle.QuoteAlways", "CsvStyle.Type", "Currency.From", "Currency.Type", "Date.AddDays", "Date.AddMonths", "Date.AddQuarters", "Date.AddWeeks", "Date.AddYears", "Date.Day", "Date.DayOfWeek", "Date.DayOfWeekName", "Date.DayOfYear", "Date.DaysInMonth", "Date.EndOfDay", "Date.EndOfMonth", "Date.EndOfQuarter", "Date.EndOfWeek", "Date.EndOfYear", "Date.From", "Date.FromText", "Date.IsInCurrentDay", "Date.IsInCurrentMonth", "Date.IsInCurrentQuarter", "Date.IsInCurrentWeek", "Date.IsInCurrentYear", "Date.IsInNextDay", "Date.IsInNextMonth", "Date.IsInNextNDays", "Date.IsInNextNMonths", "Date.IsInNextNQuarters", "Date.IsInNextNWeeks", "Date.IsInNextNYears", "Date.IsInNextQuarter", "Date.IsInNextWeek", "Date.IsInNextYear", "Date.IsInPreviousDay", "Date.IsInPreviousMonth", "Date.IsInPreviousNDays", "Date.IsInPreviousNMonths", "Date.IsInPreviousNQuarters", "Date.IsInPreviousNWeeks", "Date.IsInPreviousNYears", "Date.IsInPreviousQuarter", "Date.IsInPreviousWeek", "Date.IsInPreviousYear", "Date.IsInYearToDate", "Date.IsLeapYear", "Date.Month", "Date.MonthName", "Date.QuarterOfYear", "Date.StartOfDay", "Date.StartOfMonth", "Date.StartOfQuarter", "Date.StartOfWeek", "Date.StartOfYear", "Date.ToRecord", "Date.ToText", "Date.Type", "Date.WeekOfMonth", "Date.WeekOfYear", "Date.Year", "DateTime.AddZone", "DateTime.Date", "DateTime.From", "DateTime.FromText", "DateTime.IsInCurrentHour", "DateTime.IsInCurrentMinute", "DateTime.IsInCurrentSecond", "DateTime.IsInNextHour", "DateTime.IsInNextMinute", "DateTime.IsInNextNHours", "DateTime.IsInNextNMinutes", "DateTime.IsInNextNSeconds", "DateTime.IsInNextSecond", "DateTime.IsInPreviousHour", "DateTime.IsInPreviousMinute", "DateTime.IsInPreviousNHours", "DateTime.IsInPreviousNMinutes", "DateTime.IsInPreviousNSeconds", "DateTime.IsInPreviousSecond", "DateTime.Time", "DateTime.ToRecord", "DateTime.ToText", "DateTime.Type", "DateTimeZone.From", "DateTimeZone.FromText", "DateTimeZone.RemoveZone", "DateTimeZone.SwitchZone", "DateTimeZone.ToRecord", "DateTimeZone.ToText", "DateTimeZone.ToUtc", "DateTimeZone.Type", "DateTimeZone.ZoneHours", "DateTimeZone.ZoneMinutes", "Day.Friday", "Day.Monday", "Day.Saturday", "Day.Sunday", "Day.Thursday", "Day.Tuesday", "Day.Type", "Day.Wednesday", "Decimal.From", "Decimal.Type", "Double.From", "Double.Type", "Duration.Days", "Duration.From", "Duration.FromText", "Duration.Hours", "Duration.Minutes", "Duration.Seconds", "Duration.ToRecord", "Duration.ToText", "Duration.TotalDays", "Duration.TotalHours", "Duration.TotalMinutes", "Duration.TotalSeconds", "Duration.Type", "EmigoDataSourceConnector.NavigationFunctionType", "Error.Record", "Excel.RichDocument", "Expression.Constant", "Expression.Identifier", "ExtraValues.Error", "ExtraValues.Ignore", "ExtraValues.List", "ExtraValues.Type", "Function.From", "Function.Invoke", "Function.IsDataSource", "Function.ScalarVector", "Function.Type", "Geography.FromWellKnownText", "Geography.ToWellKnownText", "GeographyPoint.From", "Geometry.FromWellKnownText", "Geometry.ToWellKnownText", "GeometryPoint.From", "GroupKind.Global", "GroupKind.Local", "GroupKind.Type", "Guid.From", "Guid.Type", "HiveProtocol.HTTP", "HiveProtocol.Standard", "HiveProtocol.Type", "Identity.Type", "IdentityProvider.Type", "Int16.From", "Int16.Type", "Int32.From", "Int32.Type", "Int64.From", "Int64.Type", "Int8.From", "Int8.Type", "ItemExpression.From", "ItemExpression.Item", "JoinAlgorithm.Dynamic", "JoinAlgorithm.LeftHash", "JoinAlgorithm.LeftIndex", "JoinAlgorithm.PairwiseHash", "JoinAlgorithm.RightHash", "JoinAlgorithm.RightIndex", "JoinAlgorithm.SortMerge", "JoinAlgorithm.Type", "JoinKind.FullOuter", "JoinKind.Inner", "JoinKind.LeftAnti", "JoinKind.LeftOuter", "JoinKind.LeftSemi", "JoinKind.RightAnti", "JoinKind.RightOuter", "JoinKind.RightSemi", "JoinKind.Type", "JoinSide.Left", "JoinSide.Right", "JoinSide.Type", "Json.Document", "Json.FromValue", "LimitClauseKind.AnsiSql2008", "LimitClauseKind.Limit", "LimitClauseKind.LimitOffset", "LimitClauseKind.None", "LimitClauseKind.Top", "LimitClauseKind.Type", "Lines.FromBinary", "Lines.FromText", "Lines.ToBinary", "Lines.ToText", "List.Accumulate", "List.AllTrue", "List.Alternate", "List.AnyTrue", "List.Average", "List.Buffer", "List.Combine", "List.ConformToPageReader", "List.Contains", "List.ContainsAll", "List.ContainsAny", "List.Count", "List.Covariance", "List.DateTimeZones", "List.DateTimes", "List.Dates", "List.Difference", "List.Distinct", "List.Durations", "List.FindText", "List.First", "List.FirstN", "List.Generate", "List.InsertRange", "List.Intersect", "List.IsDistinct", "List.IsEmpty", "List.Last", "List.LastN", "List.MatchesAll", "List.MatchesAny", "List.Max", "List.MaxN", "List.Median", "List.Min", "List.MinN", "List.Mode", "List.Modes", "List.NonNullCount", "List.Numbers", "List.Percentile", "List.PositionOf", "List.PositionOfAny", "List.Positions", "List.Product", "List.Random", "List.Range", "List.RemoveFirstN", "List.RemoveItems", "List.RemoveLastN", "List.RemoveMatchingItems", "List.RemoveNulls", "List.RemoveRange", "List.Repeat", "List.ReplaceMatchingItems", "List.ReplaceRange", "List.ReplaceValue", "List.Reverse", "List.Select", "List.Single", "List.SingleOrDefault", "List.Skip", "List.Sort", "List.Split", "List.StandardDeviation", "List.Sum", "List.Times", "List.Transform", "List.TransformMany", "List.Type", "List.Union", "List.Zip", "Logical.From", "Logical.FromText", "Logical.ToText", "Logical.Type", "MissingField.Error", "MissingField.Ignore", "MissingField.Type", "MissingField.UseNull", "None.Type", "Null.Type", "Number.Abs", "Number.Acos", "Number.Asin", "Number.Atan", "Number.Atan2", "Number.BitwiseAnd", "Number.BitwiseNot", "Number.BitwiseOr", "Number.BitwiseShiftLeft", "Number.BitwiseShiftRight", "Number.BitwiseXor", "Number.Combinations", "Number.Cos", "Number.Cosh", "Number.E", "Number.Epsilon", "Number.Exp", "Number.Factorial", "Number.From", "Number.FromText", "Number.IntegerDivide", "Number.IsEven", "Number.IsNaN", "Number.IsOdd", "Number.Ln", "Number.Log", "Number.Log10", "Number.Mod", "Number.NaN", "Number.NegativeInfinity", "Number.PI", "Number.Permutations", "Number.PositiveInfinity", "Number.Power", "Number.Random", "Number.RandomBetween", "Number.Round", "Number.RoundAwayFromZero", "Number.RoundDown", "Number.RoundTowardZero", "Number.RoundUp", "Number.Sign", "Number.Sin", "Number.Sinh", "Number.Sqrt", "Number.Tan", "Number.Tanh", "Number.ToText", "Number.Type", "ODataOmitValues.Nulls", "ODataOmitValues.Type", "Occurrence.All", "Occurrence.First", "Occurrence.Last", "Occurrence.Optional", "Occurrence.Repeating", "Occurrence.Required", "Occurrence.Type", "Office.InferChartPropertiesGenerator", "Order.Ascending", "Order.Descending", "Order.Type", "Password.Type", "Percentage.From", "Percentage.Type", "PercentileMode.ExcelExc", "PercentileMode.ExcelInc", "PercentileMode.SqlCont", "PercentileMode.SqlDisc", "PercentileMode.Type", "PowerPoint.Presentation", "Precision.Decimal", "Precision.Double", "Precision.Type", "QuoteStyle.Csv", "QuoteStyle.None", "QuoteStyle.Type", "RankKind.Competition", "RankKind.Dense", "RankKind.Ordinal", "RankKind.Type", "Record.AddField", "Record.Combine", "Record.Field", "Record.FieldCount", "Record.FieldNames", "Record.FieldOrDefault", "Record.FieldValues", "Record.FromList", "Record.FromTable", "Record.HasFields", "Record.RemoveFields", "Record.RenameFields", "Record.ReorderFields", "Record.SelectFields", "Record.ToList", "Record.ToTable", "Record.TransformFields", "Record.Type", "RelativePosition.FromEnd", "RelativePosition.FromStart", "RelativePosition.Type", "Replacer.ReplaceText", "Replacer.ReplaceValue", "RoundingMode.AwayFromZero", "RoundingMode.Down", "RoundingMode.ToEven", "RoundingMode.TowardZero", "RoundingMode.Type", "RoundingMode.Up", "RowExpression.Column", "RowExpression.From", "RowExpression.Row", "SapBusinessWarehouseExecutionMode.BasXml", "SapBusinessWarehouseExecutionMode.BasXmlGzip", "SapBusinessWarehouseExecutionMode.DataStream", "SapBusinessWarehouseExecutionMode.Type", "SapHanaDistribution.All", "SapHanaDistribution.Connection", "SapHanaDistribution.Off", "SapHanaDistribution.Statement", "SapHanaDistribution.Type", "SapHanaRangeOperator.Equals", "SapHanaRangeOperator.GreaterThan", "SapHanaRangeOperator.GreaterThanOrEquals", "SapHanaRangeOperator.LessThan", "SapHanaRangeOperator.LessThanOrEquals", "SapHanaRangeOperator.NotEquals", "SapHanaRangeOperator.Type", "Single.From", "Single.Type", "SparkProtocol.Azure", "SparkProtocol.HTTP", "SparkProtocol.Standard", "SparkProtocol.Type", "Splitter.SplitByNothing", "Splitter.SplitTextByAnyDelimiter", "Splitter.SplitTextByCharacterTransition", "Splitter.SplitTextByDelimiter", "Splitter.SplitTextByEachDelimiter", "Splitter.SplitTextByLengths", "Splitter.SplitTextByPositions", "Splitter.SplitTextByRanges", "Splitter.SplitTextByRepeatedLengths", "Splitter.SplitTextByWhitespace", "Table.AddColumn", "Table.AddFuzzyClusterColumn", "Table.AddIndexColumn", "Table.AddJoinColumn", "Table.AddKey", "Table.AddRankColumn", "Table.AggregateTableColumn", "Table.AlternateRows", "Table.ApproximateRowCount", "Table.Buffer", "Table.ClearDown", "Table.Column", "Table.ColumnCount", "Table.ColumnNames", "Table.ColumnsOfType", "Table.Combine", "Table.CombineColumns", "Table.CombineColumnsToRecord", "Table.ConformToPageReader", "Table.Contains", "Table.ContainsAll", "Table.ContainsAny", "Table.DemoteHeaders", "Table.Distinct", "Table.DuplicateColumn", "Table.ExpandListColumn", "Table.ExpandRecordColumn", "Table.ExpandTableColumn", "Table.FillDown", "Table.FillUp", "Table.FindText", "Table.First", "Table.FirstN", "Table.FirstValue", "Table.FromColumns", "Table.FromList", "Table.FromPartitions", "Table.FromRecords", "Table.FromRows", "Table.FromValue", "Table.FuzzyGroup", "Table.FuzzyJoin", "Table.FuzzyNestedJoin", "Table.Group", "Table.HasColumns", "Table.InsertRows", "Table.IsDistinct", "Table.IsEmpty", "Table.Join", "Table.Keys", "Table.Last", "Table.LastN", "Table.MatchesAllRows", "Table.MatchesAnyRows", "Table.Max", "Table.MaxN", "Table.Min", "Table.MinN", "Table.NestedJoin", "Table.Partition", "Table.PartitionKey", "Table.PartitionValues", "Table.Pivot", "Table.PositionOf", "Table.PositionOfAny", "Table.PrefixColumns", "Table.Profile", "Table.PromoteHeaders", "Table.Range", "Table.RemoveColumns", "Table.RemoveFirstN", "Table.RemoveLastN", "Table.RemoveMatchingRows", "Table.RemoveRows", "Table.RemoveRowsWithErrors", "Table.RenameColumns", "Table.ReorderColumns", "Table.Repeat", "Table.ReplaceErrorValues", "Table.ReplaceKeys", "Table.ReplaceMatchingRows", "Table.ReplacePartitionKey", "Table.ReplaceRelationshipIdentity", "Table.ReplaceRows", "Table.ReplaceValue", "Table.ReverseRows", "Table.RowCount", "Table.Schema", "Table.SelectColumns", "Table.SelectRows", "Table.SelectRowsWithErrors", "Table.SingleRow", "Table.Skip", "Table.Sort", "Table.Split", "Table.SplitAt", "Table.SplitColumn", "Table.StopFolding", "Table.ToColumns", "Table.ToList", "Table.ToRecords", "Table.ToRows", "Table.TransformColumnNames", "Table.TransformColumnTypes", "Table.TransformColumns", "Table.TransformRows", "Table.Transpose", "Table.Type", "Table.Unpivot", "Table.UnpivotOtherColumns", "Table.View", "Table.ViewError", "Table.ViewFunction", "Table.WithErrorContext", "Tables.GetRelationships", "Text.AfterDelimiter", "Text.At", "Text.BeforeDelimiter", "Text.BetweenDelimiters", "Text.Clean", "Text.Combine", "Text.Contains", "Text.End", "Text.EndsWith", "Text.Format", "Text.From", "Text.FromBinary", "Text.InferNumberType", "Text.Insert", "Text.Length", "Text.Lower", "Text.Middle", "Text.NewGuid", "Text.PadEnd", "Text.PadStart", "Text.PositionOf", "Text.PositionOfAny", "Text.Proper", "Text.Range", "Text.Remove", "Text.RemoveRange", "Text.Repeat", "Text.Replace", "Text.ReplaceRange", "Text.Reverse", "Text.Select", "Text.Split", "Text.SplitAny", "Text.Start", "Text.StartsWith", "Text.ToBinary", "Text.ToList", "Text.Trim", "Text.TrimEnd", "Text.TrimStart", "Text.Type", "Text.Upper", "TextEncoding.Ascii", "TextEncoding.BigEndianUnicode", "TextEncoding.Type", "TextEncoding.Unicode", "TextEncoding.Utf16", "TextEncoding.Utf8", "TextEncoding.Windows", "Time.EndOfHour", "Time.From", "Time.FromText", "Time.Hour", "Time.Minute", "Time.Second", "Time.StartOfHour", "Time.ToRecord", "Time.ToText", "Time.Type", "TraceLevel.Critical", "TraceLevel.Error", "TraceLevel.Information", "TraceLevel.Type", "TraceLevel.Verbose", "TraceLevel.Warning", "Type.AddTableKey", "Type.ClosedRecord", "Type.Facets", "Type.ForFunction", "Type.ForRecord", "Type.FunctionParameters", "Type.FunctionRequiredParameters", "Type.FunctionReturn", "Type.Is", "Type.IsNullable", "Type.IsOpenRecord", "Type.ListItem", "Type.NonNullable", "Type.OpenRecord", "Type.RecordFields", "Type.ReplaceFacets", "Type.ReplaceTableKeys", "Type.ReplaceTablePartitionKey", "Type.TableColumn", "Type.TableKeys", "Type.TablePartitionKey", "Type.TableRow", "Type.TableSchema", "Type.Type", "Type.Union", "Uri.BuildQueryString", "Uri.Combine", "Uri.EscapeDataString", "Uri.Parts", "Uri.Type", "Value.Add", "Value.As", "Value.Compare", "Value.Divide", "Value.Equals", "Value.Expression", "Value.FromText", "Value.Is", "Value.Metadata", "Value.Multiply", "Value.NullableEquals", "Value.RemoveMetadata", "Value.ReplaceMetadata", "Value.ReplaceType", "Value.Subtract", "Value.Type", "WebMethod.Delete", "WebMethod.Get", "WebMethod.Head", "WebMethod.Patch", "WebMethod.Post", "WebMethod.Put", "WebMethod.Type", "Xml.Document", "Xml.Tables"},
				            Environment = Record.SelectFields(#shared, Allowed, MissingField.Ignore),
				            // A text as an M text literal: "#(" first, so the escapes added after it stay single.
				            // Every other control character as #(XXXX): written raw, it does not survive the trip
				            // back through ADOMD (U+0001 in Binary.InferContentType's delimiters was lost).
				            Controls = List.Numbers(0, 32) & List.Numbers(127, 33) & {8232, 8233},
				            Quote = (t as text) as text =>
				                let
				                    s1 = Text.Replace(t, "#(#)(", "#(#)(#)("),
				                    s2 = Text.Replace(s1, """", """"""),
				                    s3 = Text.Replace(s2, "#(cr)", "#(#)(cr)"),
				                    s4 = Text.Replace(s3, "#(lf)", "#(#)(lf)"),
				                    s5 = Text.Replace(s4, "#(tab)", "#(#)(tab)"),
				                    s6 = if Text.Length(Text.Select(s5, List.Transform(Controls, Character.FromNumber))) = 0 then s5
				                        else Text.Combine(List.Transform(Text.ToList(s5), (c) =>
				                            if List.Contains(Controls, Character.ToNumber(c))
				                            then "#(#)(" & Text.PadStart(Number.ToText(Character.ToNumber(c), "X", "en-US"), 4, "0") & ")"
				                            else c))
				                in
				                    """" & s6 & """",
				            Keywords = {"and", "as", "each", "else", "error", "false", "if", "in", "is", "let", "meta",
				                "not", "null", "or", "otherwise", "section", "shared", "then", "true", "try", "type"},
				            IdentChars = {"A".."Z", "a".."z", "0".."9", "_"},
				            Ident = (name as text) as text =>
				                if name <> "" and Text.Select(name, IdentChars) = name
				                    and not List.Contains({"0".."9"}, Text.Start(name, 1))
				                    and not List.Contains(Keywords, name)
				                then name
				                else "#" & Quote(name),
				            Num = (n as number) as text =>
				                if Number.IsNaN(n) then "#nan"
				                else if n = Number.PositiveInfinity then "#infinity"
				                else if n = Number.NegativeInfinity then "-#infinity"
				                else try Number.ToText(n, "R", "en-US") otherwise Number.ToText(n, null, "en-US"),
				            // Int64.Type, Currency.Type and friends are `number` with no facets set: what names them
				            // is Documentation.Name in their metadata. Printed only when #shared has that name, so a
				            // result can never show a type name the library does not export.
				            TypeName = (t as type) as nullable text =>
				                let
				                    n = Record.FieldOrDefault(Value.Metadata(t), "Documentation.Name", null)
				                in
				                    if n is text and Text.EndsWith(n, ".Type") and Record.HasFields(#shared, n)
				                    then n else null,
				            Primitive = (t as type) as text =>
				                let
				                    candidates = {
				                        {type logical, "logical"}, {type number, "number"}, {type time, "time"},
				                        {type date, "date"}, {type datetime, "datetime"},
				                        {type datetimezone, "datetimezone"}, {type duration, "duration"},
				                        {type text, "text"}, {type binary, "binary"}, {type type, "type"},
				                        {type list, "list"}, {type record, "record"}, {type table, "table"},
				                        {type function, "function"}, {type anynonnull, "any"}
				                    },
				                    hit = List.First(List.Select(candidates, each Type.Is(t, _{0})), null)
				                in
				                    if Type.Is(t, type none) then "none" else if hit = null then "any" else hit{1},
				            FieldsText = (fields as record, open as logical) as text =>
				                let
				                    names = Record.FieldNames(fields),
				                    parts = List.Transform(names, (n) =>
				                        let f = Record.Field(fields, n) in
				                            (if f[Optional] then "optional " else "") & Ident(n) & " = " & TypeText(f[Type])),
				                    all = if open then parts & {"..."} else parts
				                in
				                    "[" & Text.Combine(all, ", ") & "]",
				            FunctionTypeText = (t as type) as text =>
				                let
				                    params = Type.FunctionParameters(t),
				                    names = Record.FieldNames(params),
				                    required = Type.FunctionRequiredParameters(t),
				                    parts = List.Transform(List.Positions(names), (i) =>
				                        (if i >= required then "optional " else "") & Ident(names{i}) & " as "
				                            & TypeText(Record.Field(params, names{i})))
				                in
				                    "function (" & Text.Combine(parts, ", ") & ") as " & TypeText(Type.FunctionReturn(t)),
				            TypeText = (t as type) as text =>
				                let
				                    nullable = Type.IsNullable(t) and not Type.Is(t, type null),
				                    base = Type.NonNullable(t),
				                    named = TypeName(t),
				                    body =
				                        if Type.Is(t, type null) then "null"
				                        else if named <> null then named
				                        else if Type.Is(base, type table) then
				                            "table " & FieldsText(Type.RecordFields(Type.TableRow(base)), false)
				                        else if Type.Is(base, type record) then
				                            FieldsText(Type.RecordFields(base), Type.IsOpenRecord(base))
				                        // A let binding that calls itself needs @; without it the engine reports
				                        // "The import TypeText matches no exports".
				                        else if Type.Is(base, type list) then "{" & @TypeText(Type.ListItem(base)) & "}"
				                        else if Type.Is(base, type function) then FunctionTypeText(base)
				                        else Primitive(base),
				                    // `any` includes null; the same type without null is spelled anynonnull.
				                    spelled = if body = "any" and not Type.IsNullable(t) then "anynonnull" else body
				                in
				                    (if nullable and body <> "any" then "nullable " else "") & spelled,
				            ErrorText = (e as record) as text =>
				                let
				                    detail = Record.FieldOrDefault(e, "Detail", null),
				                    detailText = if detail = null then "" else " | Detail: " & Safe(() => detail)
				                in
				                    "error: " & OrEmpty(e[Reason]) & ": " & OrEmpty(e[Message]) & detailText,
				            OrEmpty = (x as any) as text => if x is null then "" else Text.From(x),
				            // Every nested value is rendered through Safe with a thunk, so an error in one cell shows
				            // as that cell's text instead of failing the whole case.
				            Safe = (get as function) as text =>
				                let r = try Render(get()) in if r[HasError] then ErrorText(r[Error]) else r[Value],
				            MaxItems = 100,
				            ListText = (items as list) as text =>
				                let
				                    head = List.FirstN(items, MaxItems + 1),
				                    shown = List.FirstN(head, MaxItems),
				                    parts = List.Transform(List.Positions(shown), (i) => Safe(() => shown{i})),
				                    more = if List.Count(head) > MaxItems then {"..."} else {}
				                in
				                    "{" & Text.Combine(parts & more, ", ") & "}",
				            TableText = (t as table) as text =>
				                let
				                    head = Table.FirstN(t, MaxItems + 1),
				                    shown = Table.FirstN(head, MaxItems),
				                    columns = Table.ColumnNames(t),
				                    rows = List.Transform(Table.ToRecords(shown), (r) =>
				                        "{" & Text.Combine(List.Transform(columns, (c) => Safe(() => Record.Field(r, c))), ", ")
				                            & "}"),
				                    more = if Table.RowCount(head) > MaxItems then {"..."} else {}
				                in
				                    "#table(type " & TypeText(Value.Type(t)) & ", {" & Text.Combine(rows & more, ", ") & "})",
				            Render = (v as any) as text =>
				                if v is null then "null"
				                else if v is logical then (if v then "true" else "false")
				                else if v is number then Num(v)
				                else if v is text then Quote(v)
				                else if v is date then
				                    "#date(" & Text.Combine(List.Transform({Date.Year(v), Date.Month(v), Date.Day(v)}, Num), ", ") & ")"
				                else if v is datetimezone then
				                    "#datetimezone(" & Text.Combine(List.Transform({Date.Year(v), Date.Month(v), Date.Day(v),
				                        Time.Hour(v), Time.Minute(v), Time.Second(v),
				                        DateTimeZone.ZoneHours(v), DateTimeZone.ZoneMinutes(v)}, Num), ", ") & ")"
				                else if v is datetime then
				                    "#datetime(" & Text.Combine(List.Transform({Date.Year(v), Date.Month(v), Date.Day(v),
				                        Time.Hour(v), Time.Minute(v), Time.Second(v)}, Num), ", ") & ")"
				                else if v is time then
				                    "#time(" & Text.Combine(List.Transform({Time.Hour(v), Time.Minute(v), Time.Second(v)}, Num), ", ") & ")"
				                else if v is duration then
				                    "#duration(" & Text.Combine(List.Transform({Duration.Days(v), Duration.Hours(v),
				                        Duration.Minutes(v), Duration.Seconds(v)}, Num), ", ") & ")"
				                else if v is binary then
				                    "#binary({" & Text.Combine(List.Transform(Binary.ToList(v), Num), ", ") & "})"
				                else if v is list then ListText(v)
				                else if v is record then
				                    "[" & Text.Combine(List.Transform(Record.FieldNames(v), (f) =>
				                        Ident(f) & " = " & Safe(() => Record.Field(v, f))), ", ") & "]"
				                else if v is table then TableText(v)
				                else if v is type then "type " & TypeText(v)
				                else if v is function then FunctionTypeText(Value.Type(v))
				                else "<" & Primitive(Value.Type(v)) & ">",
				            // Separate Expression.Evaluate calls share cached values: with the same #table literal in
				            // two cases, Table.TransformColumnNames in one made Table.Buffer in the other return the
				            // renamed columns (reproduced 2026-09-29; one query with both steps is not affected). A
				            // distinct environment per case is meant to keep each evaluation to itself.
				            Run = (i as number, code as text) as text =>
				                let r = try Render(Expression.Evaluate(code, Environment & [#"__runner case" = i])) in
				                    if r[HasError] then ErrorText(r[Error]) else r[Value],
				            Result = #table(
				                type table [seq = Int64.Type, id = text, result = text],
				                List.Transform(List.Positions(Cases), (i) => {i, Cases{i}{0}, Run(i, Cases{i}{1})})
				            )
				        in
				            Result,
				    Pages = #table(type table [seq = Int64.Type, Function = text, Block = Int64.Type, Code = text, Recorded = text], {{0, "DateTime.AddZone", 1, "DateTime.AddZone(null, 7, 30)", "null"}, {1, "DateTime.AddZone", 2, "DateTime.AddZone(#datetime(2010, 12, 31, 11, 56, 2), -5)", "#datetimezone(2010, 12, 31, 11, 56, 2, -5, 0)"}, {2, "DateTime.AddZone", 3, "DateTime.AddZone(#datetime(2200, 6, 15, 23, 59, 59), -3, -30)", "#datetimezone(2200, 6, 15, 23, 59, 59, -3, -30)"}, {3, "DateTime.Date", 1, "DateTime.Date(null)", "null"}, {4, "DateTime.Date", 2, "DateTime.Date(#datetime(1990, 1, 1, 23, 59, 59))", "#date(1990, 1, 1)"}, {5, "DateTime.Date", 3, "DateTime.Date(#datetimezone(2200, 12, 31, 0, 0, 0, 8, 0))", "#date(2200, 12, 31)"}, {6, "DateTime.From", 1, "DateTime.From(null)", "null"}, {7, "DateTime.From", 2, "DateTime.From(""12/31/1990 11:59:59 PM"", ""en-US"")", "#datetime(1990, 12, 31, 23, 59, 59)"}, {8, "DateTime.From", 3, "DateTime.From(#time(6, 45, 12))", "#datetime(1899, 12, 30, 6, 45, 12)"}, {9, "DateTime.FromText", 1, "DateTime.FromText(null)", "null"}, {10, "DateTime.FromText", 2, "DateTime.FromText(""01/02/2010 03:04:05"", ""en-GB"")", "#datetime(2010, 2, 1, 3, 4, 5)"}, {11, "DateTime.FromText", 3, "DateTime.FromText(""30 Dez 2010 02:04:50.369730"", [Format = ""dd MMM yyyy HH:mm:ss.ffffff"", Culture = ""de-DE""])", "#datetime(2010, 12, 30, 2, 4, 50.36973)"}, {12, "DateTime.IsInCurrentHour", 1, "DateTime.IsInCurrentHour(#datetime(1990, 1, 1, 0, 0, 0))", "false"}, {13, "DateTime.IsInCurrentHour", 2, "DateTime.IsInCurrentHour(#datetimezone(2200, 1, 1, 0, 0, 0, 0, 0))", "false"}, {14, "DateTime.IsInCurrentHour", 3, "DateTime.IsInCurrentHour(null)", "null"}, {15, "DateTime.IsInCurrentMinute", 1, "DateTime.IsInCurrentMinute(null)", "null"}, {16, "DateTime.IsInCurrentMinute", 2, "DateTime.IsInCurrentMinute(#datetime(1990, 12, 31, 23, 59, 0))", "false"}, {17, "DateTime.IsInCurrentMinute", 3, "DateTime.IsInCurrentMinute(#datetimezone(2200, 1, 1, 0, 0, 0, 0, 0))", "false"}, {18, "DateTime.IsInCurrentSecond", 1, "DateTime.IsInCurrentSecond(null)", "null"}, {19, "DateTime.IsInCurrentSecond", 2, "DateTime.IsInCurrentSecond(#datetime(1990, 1, 1, 0, 0, 0))", "false"}, {20, "DateTime.IsInCurrentSecond", 3, "DateTime.IsInCurrentSecond(#datetimezone(2200, 1, 1, 0, 0, 0, 0, 0))", "false"}, {21, "DateTime.IsInNextHour", 1, "DateTime.IsInNextHour(#datetime(2200, 1, 1, 0, 0, 0))", "false"}, {22, "DateTime.IsInNextHour", 2, "DateTime.IsInNextHour(#datetimezone(1990, 1, 1, 0, 0, 0, 0, 0))", "false"}, {23, "DateTime.IsInNextHour", 3, "DateTime.IsInNextHour(null)", "null"}, {24, "DateTime.IsInNextMinute", 1, "DateTime.IsInNextMinute(null)", "null"}, {25, "DateTime.IsInNextMinute", 2, "DateTime.IsInNextMinute(#datetime(1990, 1, 1, 0, 0, 0))", "false"}, {26, "DateTime.IsInNextMinute", 3, "DateTime.IsInNextMinute(#datetimezone(2200, 1, 1, 0, 0, 0, 5, 0))", "false"}, {27, "DateTime.IsInNextNHours", 1, "DateTime.IsInNextNHours(null, 3)", "null"}, {28, "DateTime.IsInNextNHours", 2, "DateTime.IsInNextNHours(#datetime(1990, 1, 1, 0, 0, 0), 3)", "false"}, {29, "DateTime.IsInNextNHours", 3, "DateTime.IsInNextNHours(#datetime(2200, 1, 1, 0, 0, 0), 2000000)", "true"}, {30, "DateTime.IsInNextNMinutes", 1, "DateTime.IsInNextNMinutes(null, 5)", "null"}, {31, "DateTime.IsInNextNMinutes", 2, "DateTime.IsInNextNMinutes(#datetime(1990, 12, 31, 23, 59, 0), 5)", "false"}, {32, "DateTime.IsInNextNMinutes", 3, "DateTime.IsInNextNMinutes(#datetimezone(2200, 1, 1, 0, 0, 0, 0, 0), 60)", "false"}, {33, "DateTime.IsInNextNSeconds", 1, "DateTime.IsInNextNSeconds(null, 10)", "null"}, {34, "DateTime.IsInNextNSeconds", 2, "DateTime.IsInNextNSeconds(#datetime(1990, 1, 1, 0, 0, 0), 60)", "false"}, {35, "DateTime.IsInNextNSeconds", 3, "DateTime.IsInNextNSeconds(#datetimezone(2200, 1, 1, 0, 0, 0, 0, 0), 10000000000)", "true"}, {36, "DateTime.IsInNextSecond", 1, "DateTime.IsInNextSecond(null)", "null"}, {37, "DateTime.IsInNextSecond", 2, "DateTime.IsInNextSecond(#datetime(1990, 12, 31, 23, 59, 59))", "false"}, {38, "DateTime.IsInNextSecond", 3, "DateTime.IsInNextSecond(#datetimezone(2200, 1, 1, 0, 0, 0, 0, 0))", "false"}, {39, "DateTime.IsInPreviousHour", 1, "DateTime.IsInPreviousHour(null)", "null"}, {40, "DateTime.IsInPreviousHour", 2, "DateTime.IsInPreviousHour(#datetime(1990, 1, 1, 0, 0, 0))", "false"}, {41, "DateTime.IsInPreviousHour", 3, "DateTime.IsInPreviousHour(#datetimezone(2200, 1, 1, 0, 0, 0, 0, 0))", "false"}, {42, "DateTime.IsInPreviousMinute", 1, "DateTime.IsInPreviousMinute(null)", "null"}, {43, "DateTime.IsInPreviousMinute", 2, "DateTime.IsInPreviousMinute(#datetime(1990, 1, 1, 0, 0, 0))", "false"}, {44, "DateTime.IsInPreviousMinute", 3, "DateTime.IsInPreviousMinute(#datetimezone(2200, 1, 1, 0, 0, 0, 0, 0))", "false"}, {45, "DateTime.IsInPreviousNHours", 1, "DateTime.IsInPreviousNHours(null, 2)", "null"}, {46, "DateTime.IsInPreviousNHours", 2, "DateTime.IsInPreviousNHours(#datetime(1990, 1, 1, 0, 0, 0), 2)", "false"}, {47, "DateTime.IsInPreviousNHours", 3, "DateTime.IsInPreviousNHours(#datetimezone(2200, 1, 1, 0, 0, 0, 0, 0), 2)", "false"}, {48, "DateTime.IsInPreviousNMinutes", 1, "DateTime.IsInPreviousNMinutes(#datetime(1990, 1, 1, 0, 0, 0), 5)", "false"}, {49, "DateTime.IsInPreviousNMinutes", 2, "DateTime.IsInPreviousNMinutes(#datetimezone(2200, 1, 1, 0, 0, 0, 0, 0), 5)", "false"}, {50, "DateTime.IsInPreviousNMinutes", 3, "DateTime.IsInPreviousNMinutes(null, 5)", "null"}, {51, "DateTime.IsInPreviousNSeconds", 1, "DateTime.IsInPreviousNSeconds(null, 10)", "null"}, {52, "DateTime.IsInPreviousNSeconds", 2, "DateTime.IsInPreviousNSeconds(#datetime(1990, 1, 1, 0, 0, 0), 60)", "false"}, {53, "DateTime.IsInPreviousNSeconds", 3, "DateTime.IsInPreviousNSeconds(#datetimezone(2200, 12, 31, 23, 59, 59, 0, 0), 60)", "false"}, {54, "DateTime.IsInPreviousSecond", 1, "DateTime.IsInPreviousSecond(#datetime(1990, 1, 1, 0, 0, 0))", "false"}, {55, "DateTime.IsInPreviousSecond", 2, "DateTime.IsInPreviousSecond(null)", "null"}, {56, "DateTime.IsInPreviousSecond", 3, "DateTime.IsInPreviousSecond(#datetimezone(2200, 1, 1, 0, 0, 0, 0, 0))", "false"}, {57, "DateTime.Time", 1, "DateTime.Time(#datetime(2200, 6, 15, 4, 5, 6))", "#time(4, 5, 6)"}, {58, "DateTime.Time", 2, "DateTime.Time(#date(1990, 1, 1))", "error: Expression.Error: The DateTime.Time function expects an input of type DateTime or DateTimeZone. | Detail: #date(1990, 1, 1)"}, {59, "DateTime.Time", 3, "DateTime.Time(null)", "null"}, {60, "DateTime.ToRecord", 1, "DateTime.ToRecord(#datetime(1990, 3, 15, 13, 45, 30))", "[Year = 1990, Month = 3, Day = 15, Hour = 13, Minute = 45, Second = 30]"}, {61, "DateTime.ToRecord", 2, "DateTime.ToRecord(null)", "error: Expression.Error: We cannot convert the value null to type DateTime. | Detail: [Value = null, Type = type datetime]"}, {62, "DateTime.ToRecord", 3, "DateTime.ToRecord(#datetime(2200, 12, 31, 23, 59, 59.5))", "[Year = 2200, Month = 12, Day = 31, Hour = 23, Minute = 59, Second = 59.5]"}, {63, "DateTime.ToText", 1, "DateTime.ToText(null)", "null"}, {64, "DateTime.ToText", 2, "DateTime.ToText(#datetime(2010, 12, 30, 2, 4, 50.36973), ""dd MMM yyyy"", ""de-DE"")", """30 Dez 2010"""}, {65, "DateTime.ToText", 3, "DateTime.ToText(#datetime(2010, 12, 31, 13, 30, 25), [Format = null, Culture = ""en-US""])", """12/31/2010 1:30:25 PM"""}}),
				    Joined = Table.NestedJoin(Pages, "seq", Table.TransformColumns(Live, {{"id", Number.From}}), "id", "L", JoinKind.LeftOuter),
				    Expanded = Table.ExpandTableColumn(Joined, "L", {"result"}, {"Live"}),
				    Matched = Table.AddColumn(Expanded, "Match", each if [Live] = [Recorded] then "yes" else "NO", type text),
				    Sorted = Table.Sort(Matched, {{"seq", Order.Ascending}})
				in
				    Sorted

	annotation PBI_ResultType = Table
