/// Generated by lab/review/build_review.py from the example pages. Do not edit.
table TableRowOperations
	lineageTag: 19fb0fc5-7550-56a6-83b8-94c0f1b75b08

	column seq
		dataType: int64
		lineageTag: de3bfcf5-b2e7-5b42-99b3-ec971b78c85e
		summarizeBy: none
		sourceColumn: seq

	column Function
		dataType: string
		lineageTag: 48a07a39-cc90-5cbe-b7c0-427b6a5a5b9a
		summarizeBy: none
		sourceColumn: Function

	column Description
		dataType: string
		lineageTag: 28107d45-b8ec-5fe6-a9ba-3b1e81e53736
		summarizeBy: none
		sourceColumn: Description

	column Block
		dataType: int64
		lineageTag: c9f2ebf8-62c4-554d-bf14-9af70972d4a9
		summarizeBy: none
		sourceColumn: Block

	column Code
		dataType: string
		lineageTag: 7cb2227b-8af7-5406-ab83-d4bd55435600
		summarizeBy: none
		sourceColumn: Code

	column Recorded
		dataType: string
		lineageTag: 4d25c487-bb54-5258-bb8c-f8c9f358b5a7
		summarizeBy: none
		sourceColumn: Recorded

	column Live
		dataType: string
		lineageTag: 6b4b3892-707b-5150-9d53-7faed7086809
		summarizeBy: none
		sourceColumn: Live

	column Match
		dataType: string
		lineageTag: aee3b62a-29a0-524f-a8a1-d471ea5d6b79
		summarizeBy: none
		sourceColumn: Match

	measure Examples = COUNTROWS('TableRowOperations')
		formatString: 0
		lineageTag: ae9e02ab-121b-5582-9153-a11d213c1f18

	partition TableRowOperations = m
		mode: import
		source =
				let
				    Live = 
				        // runner.pq - evaluates every ```m block of the skills in the engine and renders each result
				        // as M literal text, so a page can quote what the engine returned instead of what we expect.
				        //
				        // run_examples.py replaces the Cases line with the blocks it collected and builds a PBIP
				        // whose only partition is this query. It also replaces the Allowed line with the names
				        // m_blocks.allowed_names lets a block use, and each case is evaluated with Expression.Evaluate
				        // over those members of #shared only: no data sources, no connectors, no other queries, no
				        // Expression.Evaluate - even for a name m_blocks.unsafe_calls could not see.
				        let
				            Cases = {{"0", "Table.AlternateRows(#table({""n""}, {{1}, {2}, {3}, {4}, {5}}), 1, 1, 1)"}, {"1", "Table.Combine({#table({""a""}, {{1}}), #table({""b""}, {{2}})})"}, {"2", "let#(lf)    T = #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}, {""a"", 3}})#(lf)in#(lf)    Table.FindText(T, ""b"")"}, {"3", "let#(lf)    T = #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}, {""a"", 3}})#(lf)in#(lf)    {Table.First(T), Table.First(#table({""a""}, {}))}"}, {"4", "let#(lf)    T = #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}, {""a"", 3}})#(lf)in#(lf)    {Table.FirstN(T, 2), Table.FirstN(T, each [Name] = ""a"")}"}, {"5", "let#(lf)    T = #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}, {""a"", 3}})#(lf)in#(lf)    Table.FirstValue(T)"}, {"6", "Table.FromPartitions(""Year"", {{2023, #table({""v""}, {{1}})}, {2024, #table({""v""}, {{2}})}}, Int64.Type)"}, {"7", "let#(lf)    T = #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}, {""a"", 3}})#(lf)in#(lf)    Table.InsertRows(T, 1, {[Name = ""z"", Qty = 9]})"}, {"8", "let#(lf)    T = #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}, {""a"", 3}})#(lf)in#(lf)    Table.Last(T)"}, {"9", "let#(lf)    T = #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}, {""a"", 3}})#(lf)in#(lf)    Table.LastN(T, 2)"}, {"10", "let#(lf)    T = #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}, {""a"", 3}})#(lf)in#(lf)    Table.MatchesAllRows(T, each [Qty] > 0)"}, {"11", "let#(lf)    T = #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}, {""a"", 3}})#(lf)in#(lf)    Table.MatchesAnyRows(T, each [Qty] > 2)"}, {"12", "Table.Partition(#table({""n""}, {{1}, {2}, {3}, {4}}), ""n"", 2, each _)"}, {"13", "let#(lf)    T = #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}, {""a"", 3}})#(lf)in#(lf)    Table.Range(T, 1, 1)"}, {"14", "let#(lf)    T = #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}, {""a"", 3}})#(lf)in#(lf)    Table.RemoveFirstN(T, 1)"}, {"15", "let#(lf)    T = #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}, {""a"", 3}})#(lf)in#(lf)    Table.RemoveLastN(T, 1)"}, {"16", "let#(lf)    T = #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}, {""a"", 3}})#(lf)in#(lf)    Table.RemoveRows(T, 0, 2)"}, {"17", "Table.RemoveRowsWithErrors(Table.TransformColumnTypes(#table({""v""}, {{""1""}, {""x""}}), {{""v"", Int64.Type}}))"}, {"18", "Table.Repeat(#table({""a""}, {{1}}), 3)"}, {"19", "let#(lf)    T = #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}, {""a"", 3}})#(lf)in#(lf)    Table.ReplaceRows(T, 0, 1, {[Name = ""z"", Qty = 0]})"}, {"20", "let#(lf)    T = #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}, {""a"", 3}})#(lf)in#(lf)    Table.ReverseRows(T)"}, {"21", "let#(lf)    T = #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}, {""a"", 3}})#(lf)in#(lf)    Table.SelectRows(T, each [Qty] >= 2)"}, {"22", "Table.SelectRowsWithErrors(Table.TransformColumnTypes(#table({""v""}, {{""1""}, {""x""}}), {{""v"", Int64.Type}}))"}, {"23", "let#(lf)    T = #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}, {""a"", 3}})#(lf)in#(lf)    {Table.SingleRow(#table({""a""}, {{1}})), Table.SingleRow(T)}"}, {"24", "let#(lf)    T = #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}, {""a"", 3}})#(lf)in#(lf)    Table.Skip(T, 1)"}, {"25", "let#(lf)    T = #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}, {""a"", 3}})#(lf)in#(lf)    Table.SplitAt(T, 1)"}},
				            Allowed = {"AccessControlEntry.ConditionContextType", "AccessControlEntry.Type", "AccessControlKind.Allow", "AccessControlKind.Deny", "AccessControlKind.Type", "Any.Type", "Binary.ApproximateLength", "Binary.Buffer", "Binary.Combine", "Binary.Compress", "Binary.Decompress", "Binary.From", "Binary.FromList", "Binary.FromText", "Binary.InferContentType", "Binary.Length", "Binary.Range", "Binary.Split", "Binary.ToList", "Binary.ToText", "Binary.Type", "Binary.View", "Binary.ViewError", "Binary.ViewFunction", "BinaryEncoding.Base64", "BinaryEncoding.Hex", "BinaryEncoding.Type", "BinaryFormat.7BitEncodedSignedInteger", "BinaryFormat.7BitEncodedUnsignedInteger", "BinaryFormat.Binary", "BinaryFormat.Byte", "BinaryFormat.ByteOrder", "BinaryFormat.Choice", "BinaryFormat.Decimal", "BinaryFormat.Double", "BinaryFormat.Group", "BinaryFormat.Length", "BinaryFormat.List", "BinaryFormat.Null", "BinaryFormat.Record", "BinaryFormat.SignedInteger16", "BinaryFormat.SignedInteger32", "BinaryFormat.SignedInteger64", "BinaryFormat.Single", "BinaryFormat.Text", "BinaryFormat.Transform", "BinaryFormat.UnsignedInteger16", "BinaryFormat.UnsignedInteger32", "BinaryFormat.UnsignedInteger64", "BinaryOccurrence.Optional", "BinaryOccurrence.Repeating", "BinaryOccurrence.Required", "BinaryOccurrence.Type", "BufferMode.Delayed", "BufferMode.Eager", "BufferMode.Type", "Byte.From", "Byte.Type", "ByteOrder.BigEndian", "ByteOrder.LittleEndian", "ByteOrder.Type", "Certificate.Type", "Character.FromNumber", "Character.ToNumber", "Character.Type", "Combiner.CombineTextByDelimiter", "Combiner.CombineTextByEachDelimiter", "Combiner.CombineTextByLengths", "Combiner.CombineTextByPositions", "Combiner.CombineTextByRanges", "Comparer.Equals", "Comparer.FromCulture", "Comparer.Ordinal", "Comparer.OrdinalIgnoreCase", "Compression.Brotli", "Compression.Deflate", "Compression.GZip", "Compression.LZ4", "Compression.None", "Compression.Snappy", "Compression.Type", "Compression.Zstandard", "Csv.Document", "CsvStyle.QuoteAfterDelimiter", "CsvStyle.QuoteAlways", "CsvStyle.Type", "Currency.From", "Currency.Type", "Date.AddDays", "Date.AddMonths", "Date.AddQuarters", "Date.AddWeeks", "Date.AddYears", "Date.Day", "Date.DayOfWeek", "Date.DayOfWeekName", "Date.DayOfYear", "Date.DaysInMonth", "Date.EndOfDay", "Date.EndOfMonth", "Date.EndOfQuarter", "Date.EndOfWeek", "Date.EndOfYear", "Date.From", "Date.FromText", "Date.IsInCurrentDay", "Date.IsInCurrentMonth", "Date.IsInCurrentQuarter", "Date.IsInCurrentWeek", "Date.IsInCurrentYear", "Date.IsInNextDay", "Date.IsInNextMonth", "Date.IsInNextNDays", "Date.IsInNextNMonths", "Date.IsInNextNQuarters", "Date.IsInNextNWeeks", "Date.IsInNextNYears", "Date.IsInNextQuarter", "Date.IsInNextWeek", "Date.IsInNextYear", "Date.IsInPreviousDay", "Date.IsInPreviousMonth", "Date.IsInPreviousNDays", "Date.IsInPreviousNMonths", "Date.IsInPreviousNQuarters", "Date.IsInPreviousNWeeks", "Date.IsInPreviousNYears", "Date.IsInPreviousQuarter", "Date.IsInPreviousWeek", "Date.IsInPreviousYear", "Date.IsInYearToDate", "Date.IsLeapYear", "Date.Month", "Date.MonthName", "Date.QuarterOfYear", "Date.StartOfDay", "Date.StartOfMonth", "Date.StartOfQuarter", "Date.StartOfWeek", "Date.StartOfYear", "Date.ToRecord", "Date.ToText", "Date.Type", "Date.WeekOfMonth", "Date.WeekOfYear", "Date.Year", "DateTime.AddZone", "DateTime.Date", "DateTime.From", "DateTime.FromText", "DateTime.IsInCurrentHour", "DateTime.IsInCurrentMinute", "DateTime.IsInCurrentSecond", "DateTime.IsInNextHour", "DateTime.IsInNextMinute", "DateTime.IsInNextNHours", "DateTime.IsInNextNMinutes", "DateTime.IsInNextNSeconds", "DateTime.IsInNextSecond", "DateTime.IsInPreviousHour", "DateTime.IsInPreviousMinute", "DateTime.IsInPreviousNHours", "DateTime.IsInPreviousNMinutes", "DateTime.IsInPreviousNSeconds", "DateTime.IsInPreviousSecond", "DateTime.Time", "DateTime.ToRecord", "DateTime.ToText", "DateTime.Type", "DateTimeZone.From", "DateTimeZone.FromText", "DateTimeZone.RemoveZone", "DateTimeZone.SwitchZone", "DateTimeZone.ToRecord", "DateTimeZone.ToText", "DateTimeZone.ToUtc", "DateTimeZone.Type", "DateTimeZone.ZoneHours", "DateTimeZone.ZoneMinutes", "Day.Friday", "Day.Monday", "Day.Saturday", "Day.Sunday", "Day.Thursday", "Day.Tuesday", "Day.Type", "Day.Wednesday", "Decimal.From", "Decimal.Type", "Double.From", "Double.Type", "Duration.Days", "Duration.From", "Duration.FromText", "Duration.Hours", "Duration.Minutes", "Duration.Seconds", "Duration.ToRecord", "Duration.ToText", "Duration.TotalDays", "Duration.TotalHours", "Duration.TotalMinutes", "Duration.TotalSeconds", "Duration.Type", "EmigoDataSourceConnector.NavigationFunctionType", "Error.Record", "Excel.RichDocument", "Expression.Constant", "Expression.Identifier", "ExtraValues.Error", "ExtraValues.Ignore", "ExtraValues.List", "ExtraValues.Type", "Function.From", "Function.Invoke", "Function.IsDataSource", "Function.ScalarVector", "Function.Type", "Geography.FromWellKnownText", "Geography.ToWellKnownText", "GeographyPoint.From", "Geometry.FromWellKnownText", "Geometry.ToWellKnownText", "GeometryPoint.From", "GroupKind.Global", "GroupKind.Local", "GroupKind.Type", "Guid.From", "Guid.Type", "HiveProtocol.HTTP", "HiveProtocol.Standard", "HiveProtocol.Type", "Identity.Type", "IdentityProvider.Type", "Int16.From", "Int16.Type", "Int32.From", "Int32.Type", "Int64.From", "Int64.Type", "Int8.From", "Int8.Type", "ItemExpression.From", "ItemExpression.Item", "JoinAlgorithm.Dynamic", "JoinAlgorithm.LeftHash", "JoinAlgorithm.LeftIndex", "JoinAlgorithm.PairwiseHash", "JoinAlgorithm.RightHash", "JoinAlgorithm.RightIndex", "JoinAlgorithm.SortMerge", "JoinAlgorithm.Type", "JoinKind.FullOuter", "JoinKind.Inner", "JoinKind.LeftAnti", "JoinKind.LeftOuter", "JoinKind.LeftSemi", "JoinKind.RightAnti", "JoinKind.RightOuter", "JoinKind.RightSemi", "JoinKind.Type", "JoinSide.Left", "JoinSide.Right", "JoinSide.Type", "Json.Document", "Json.FromValue", "LimitClauseKind.AnsiSql2008", "LimitClauseKind.Limit", "LimitClauseKind.LimitOffset", "LimitClauseKind.None", "LimitClauseKind.Top", "LimitClauseKind.Type", "Lines.FromBinary", "Lines.FromText", "Lines.ToBinary", "Lines.ToText", "List.Accumulate", "List.AllTrue", "List.Alternate", "List.AnyTrue", "List.Average", "List.Buffer", "List.Combine", "List.ConformToPageReader", "List.Contains", "List.ContainsAll", "List.ContainsAny", "List.Count", "List.Covariance", "List.DateTimeZones", "List.DateTimes", "List.Dates", "List.Difference", "List.Distinct", "List.Durations", "List.FindText", "List.First", "List.FirstN", "List.Generate", "List.InsertRange", "List.Intersect", "List.IsDistinct", "List.IsEmpty", "List.Last", "List.LastN", "List.MatchesAll", "List.MatchesAny", "List.Max", "List.MaxN", "List.Median", "List.Min", "List.MinN", "List.Mode", "List.Modes", "List.NonNullCount", "List.Numbers", "List.Percentile", "List.PositionOf", "List.PositionOfAny", "List.Positions", "List.Product", "List.Random", "List.Range", "List.RemoveFirstN", "List.RemoveItems", "List.RemoveLastN", "List.RemoveMatchingItems", "List.RemoveNulls", "List.RemoveRange", "List.Repeat", "List.ReplaceMatchingItems", "List.ReplaceRange", "List.ReplaceValue", "List.Reverse", "List.Select", "List.Single", "List.SingleOrDefault", "List.Skip", "List.Sort", "List.Split", "List.StandardDeviation", "List.Sum", "List.Times", "List.Transform", "List.TransformMany", "List.Type", "List.Union", "List.Zip", "Logical.From", "Logical.FromText", "Logical.ToText", "Logical.Type", "MissingField.Error", "MissingField.Ignore", "MissingField.Type", "MissingField.UseNull", "None.Type", "Null.Type", "Number.Abs", "Number.Acos", "Number.Asin", "Number.Atan", "Number.Atan2", "Number.BitwiseAnd", "Number.BitwiseNot", "Number.BitwiseOr", "Number.BitwiseShiftLeft", "Number.BitwiseShiftRight", "Number.BitwiseXor", "Number.Combinations", "Number.Cos", "Number.Cosh", "Number.E", "Number.Epsilon", "Number.Exp", "Number.Factorial", "Number.From", "Number.FromText", "Number.IntegerDivide", "Number.IsEven", "Number.IsNaN", "Number.IsOdd", "Number.Ln", "Number.Log", "Number.Log10", "Number.Mod", "Number.NaN", "Number.NegativeInfinity", "Number.PI", "Number.Permutations", "Number.PositiveInfinity", "Number.Power", "Number.Random", "Number.RandomBetween", "Number.Round", "Number.RoundAwayFromZero", "Number.RoundDown", "Number.RoundTowardZero", "Number.RoundUp", "Number.Sign", "Number.Sin", "Number.Sinh", "Number.Sqrt", "Number.Tan", "Number.Tanh", "Number.ToText", "Number.Type", "ODataOmitValues.Nulls", "ODataOmitValues.Type", "Occurrence.All", "Occurrence.First", "Occurrence.Last", "Occurrence.Optional", "Occurrence.Repeating", "Occurrence.Required", "Occurrence.Type", "Office.InferChartPropertiesGenerator", "Order.Ascending", "Order.Descending", "Order.Type", "Password.Type", "Percentage.From", "Percentage.Type", "PercentileMode.ExcelExc", "PercentileMode.ExcelInc", "PercentileMode.SqlCont", "PercentileMode.SqlDisc", "PercentileMode.Type", "PowerPoint.Presentation", "Precision.Decimal", "Precision.Double", "Precision.Type", "QuoteStyle.Csv", "QuoteStyle.None", "QuoteStyle.Type", "RankKind.Competition", "RankKind.Dense", "RankKind.Ordinal", "RankKind.Type", "Record.AddField", "Record.Combine", "Record.Field", "Record.FieldCount", "Record.FieldNames", "Record.FieldOrDefault", "Record.FieldValues", "Record.FromList", "Record.FromTable", "Record.HasFields", "Record.RemoveFields", "Record.RenameFields", "Record.ReorderFields", "Record.SelectFields", "Record.ToList", "Record.ToTable", "Record.TransformFields", "Record.Type", "RelativePosition.FromEnd", "RelativePosition.FromStart", "RelativePosition.Type", "Replacer.ReplaceText", "Replacer.ReplaceValue", "RoundingMode.AwayFromZero", "RoundingMode.Down", "RoundingMode.ToEven", "RoundingMode.TowardZero", "RoundingMode.Type", "RoundingMode.Up", "RowExpression.Column", "RowExpression.From", "RowExpression.Row", "SapBusinessWarehouseExecutionMode.BasXml", "SapBusinessWarehouseExecutionMode.BasXmlGzip", "SapBusinessWarehouseExecutionMode.DataStream", "SapBusinessWarehouseExecutionMode.Type", "SapHanaDistribution.All", "SapHanaDistribution.Connection", "SapHanaDistribution.Off", "SapHanaDistribution.Statement", "SapHanaDistribution.Type", "SapHanaRangeOperator.Equals", "SapHanaRangeOperator.GreaterThan", "SapHanaRangeOperator.GreaterThanOrEquals", "SapHanaRangeOperator.LessThan", "SapHanaRangeOperator.LessThanOrEquals", "SapHanaRangeOperator.NotEquals", "SapHanaRangeOperator.Type", "Single.From", "Single.Type", "SparkProtocol.Azure", "SparkProtocol.HTTP", "SparkProtocol.Standard", "SparkProtocol.Type", "Splitter.SplitByNothing", "Splitter.SplitTextByAnyDelimiter", "Splitter.SplitTextByCharacterTransition", "Splitter.SplitTextByDelimiter", "Splitter.SplitTextByEachDelimiter", "Splitter.SplitTextByLengths", "Splitter.SplitTextByPositions", "Splitter.SplitTextByRanges", "Splitter.SplitTextByRepeatedLengths", "Splitter.SplitTextByWhitespace", "Table.AddColumn", "Table.AddFuzzyClusterColumn", "Table.AddIndexColumn", "Table.AddJoinColumn", "Table.AddKey", "Table.AddRankColumn", "Table.AggregateTableColumn", "Table.AlternateRows", "Table.ApproximateRowCount", "Table.Buffer", "Table.ClearDown", "Table.Column", "Table.ColumnCount", "Table.ColumnNames", "Table.ColumnsOfType", "Table.Combine", "Table.CombineColumns", "Table.CombineColumnsToRecord", "Table.ConformToPageReader", "Table.Contains", "Table.ContainsAll", "Table.ContainsAny", "Table.DemoteHeaders", "Table.Distinct", "Table.DuplicateColumn", "Table.ExpandListColumn", "Table.ExpandRecordColumn", "Table.ExpandTableColumn", "Table.FillDown", "Table.FillUp", "Table.FindText", "Table.First", "Table.FirstN", "Table.FirstValue", "Table.FromColumns", "Table.FromList", "Table.FromPartitions", "Table.FromRecords", "Table.FromRows", "Table.FromValue", "Table.FuzzyGroup", "Table.FuzzyJoin", "Table.FuzzyNestedJoin", "Table.Group", "Table.HasColumns", "Table.InsertRows", "Table.IsDistinct", "Table.IsEmpty", "Table.Join", "Table.Keys", "Table.Last", "Table.LastN", "Table.MatchesAllRows", "Table.MatchesAnyRows", "Table.Max", "Table.MaxN", "Table.Min", "Table.MinN", "Table.NestedJoin", "Table.Partition", "Table.PartitionKey", "Table.PartitionValues", "Table.Pivot", "Table.PositionOf", "Table.PositionOfAny", "Table.PrefixColumns", "Table.Profile", "Table.PromoteHeaders", "Table.Range", "Table.RemoveColumns", "Table.RemoveFirstN", "Table.RemoveLastN", "Table.RemoveMatchingRows", "Table.RemoveRows", "Table.RemoveRowsWithErrors", "Table.RenameColumns", "Table.ReorderColumns", "Table.Repeat", "Table.ReplaceErrorValues", "Table.ReplaceKeys", "Table.ReplaceMatchingRows", "Table.ReplacePartitionKey", "Table.ReplaceRelationshipIdentity", "Table.ReplaceRows", "Table.ReplaceValue", "Table.ReverseRows", "Table.RowCount", "Table.Schema", "Table.SelectColumns", "Table.SelectRows", "Table.SelectRowsWithErrors", "Table.SingleRow", "Table.Skip", "Table.Sort", "Table.Split", "Table.SplitAt", "Table.SplitColumn", "Table.StopFolding", "Table.ToColumns", "Table.ToList", "Table.ToRecords", "Table.ToRows", "Table.TransformColumnNames", "Table.TransformColumnTypes", "Table.TransformColumns", "Table.TransformRows", "Table.Transpose", "Table.Type", "Table.Unpivot", "Table.UnpivotOtherColumns", "Table.View", "Table.ViewError", "Table.ViewFunction", "Table.WithErrorContext", "Tables.GetRelationships", "Text.AfterDelimiter", "Text.At", "Text.BeforeDelimiter", "Text.BetweenDelimiters", "Text.Clean", "Text.Combine", "Text.Contains", "Text.End", "Text.EndsWith", "Text.Format", "Text.From", "Text.FromBinary", "Text.InferNumberType", "Text.Insert", "Text.Length", "Text.Lower", "Text.Middle", "Text.NewGuid", "Text.PadEnd", "Text.PadStart", "Text.PositionOf", "Text.PositionOfAny", "Text.Proper", "Text.Range", "Text.Remove", "Text.RemoveRange", "Text.Repeat", "Text.Replace", "Text.ReplaceRange", "Text.Reverse", "Text.Select", "Text.Split", "Text.SplitAny", "Text.Start", "Text.StartsWith", "Text.ToBinary", "Text.ToList", "Text.Trim", "Text.TrimEnd", "Text.TrimStart", "Text.Type", "Text.Upper", "TextEncoding.Ascii", "TextEncoding.BigEndianUnicode", "TextEncoding.Type", "TextEncoding.Unicode", "TextEncoding.Utf16", "TextEncoding.Utf8", "TextEncoding.Windows", "Time.EndOfHour", "Time.From", "Time.FromText", "Time.Hour", "Time.Minute", "Time.Second", "Time.StartOfHour", "Time.ToRecord", "Time.ToText", "Time.Type", "TraceLevel.Critical", "TraceLevel.Error", "TraceLevel.Information", "TraceLevel.Type", "TraceLevel.Verbose", "TraceLevel.Warning", "Type.AddTableKey", "Type.ClosedRecord", "Type.Facets", "Type.ForFunction", "Type.ForRecord", "Type.FunctionParameters", "Type.FunctionRequiredParameters", "Type.FunctionReturn", "Type.Is", "Type.IsNullable", "Type.IsOpenRecord", "Type.ListItem", "Type.NonNullable", "Type.OpenRecord", "Type.RecordFields", "Type.ReplaceFacets", "Type.ReplaceTableKeys", "Type.ReplaceTablePartitionKey", "Type.TableColumn", "Type.TableKeys", "Type.TablePartitionKey", "Type.TableRow", "Type.TableSchema", "Type.Type", "Type.Union", "Uri.BuildQueryString", "Uri.Combine", "Uri.EscapeDataString", "Uri.Parts", "Uri.Type", "Value.Add", "Value.As", "Value.Compare", "Value.Divide", "Value.Equals", "Value.Expression", "Value.FromText", "Value.Is", "Value.Metadata", "Value.Multiply", "Value.NullableEquals", "Value.RemoveMetadata", "Value.ReplaceMetadata", "Value.ReplaceType", "Value.Subtract", "Value.Type", "WebMethod.Delete", "WebMethod.Get", "WebMethod.Head", "WebMethod.Patch", "WebMethod.Post", "WebMethod.Put", "WebMethod.Type", "Xml.Document", "Xml.Tables"},
				            Environment = Record.SelectFields(#shared, Allowed, MissingField.Ignore),
				            // A text as an M text literal: "#(" first, so the escapes added after it stay single.
				            // Every other control character as #(XXXX): written raw, it does not survive the trip
				            // back through ADOMD (U+0001 in Binary.InferContentType's delimiters was lost).
				            Controls = List.Numbers(0, 32) & List.Numbers(127, 33) & {8232, 8233},
				            Quote = (t as text) as text =>
				                let
				                    s1 = Text.Replace(t, "#(#)(", "#(#)(#)("),
				                    s2 = Text.Replace(s1, """", """"""),
				                    s3 = Text.Replace(s2, "#(cr)", "#(#)(cr)"),
				                    s4 = Text.Replace(s3, "#(lf)", "#(#)(lf)"),
				                    s5 = Text.Replace(s4, "#(tab)", "#(#)(tab)"),
				                    s6 = if Text.Length(Text.Select(s5, List.Transform(Controls, Character.FromNumber))) = 0 then s5
				                        else Text.Combine(List.Transform(Text.ToList(s5), (c) =>
				                            if List.Contains(Controls, Character.ToNumber(c))
				                            then "#(#)(" & Text.PadStart(Number.ToText(Character.ToNumber(c), "X", "en-US"), 4, "0") & ")"
				                            else c))
				                in
				                    """" & s6 & """",
				            Keywords = {"and", "as", "each", "else", "error", "false", "if", "in", "is", "let", "meta",
				                "not", "null", "or", "otherwise", "section", "shared", "then", "true", "try", "type"},
				            IdentChars = {"A".."Z", "a".."z", "0".."9", "_"},
				            Ident = (name as text) as text =>
				                if name <> "" and Text.Select(name, IdentChars) = name
				                    and not List.Contains({"0".."9"}, Text.Start(name, 1))
				                    and not List.Contains(Keywords, name)
				                then name
				                else "#" & Quote(name),
				            Num = (n as number) as text =>
				                if Number.IsNaN(n) then "#nan"
				                else if n = Number.PositiveInfinity then "#infinity"
				                else if n = Number.NegativeInfinity then "-#infinity"
				                else try Number.ToText(n, "R", "en-US") otherwise Number.ToText(n, null, "en-US"),
				            // Int64.Type, Currency.Type and friends are `number` with no facets set: what names them
				            // is Documentation.Name in their metadata. Printed only when #shared has that name, so a
				            // result can never show a type name the library does not export.
				            TypeName = (t as type) as nullable text =>
				                let
				                    n = Record.FieldOrDefault(Value.Metadata(t), "Documentation.Name", null)
				                in
				                    if n is text and Text.EndsWith(n, ".Type") and Record.HasFields(#shared, n)
				                    then n else null,
				            Primitive = (t as type) as text =>
				                let
				                    candidates = {
				                        {type logical, "logical"}, {type number, "number"}, {type time, "time"},
				                        {type date, "date"}, {type datetime, "datetime"},
				                        {type datetimezone, "datetimezone"}, {type duration, "duration"},
				                        {type text, "text"}, {type binary, "binary"}, {type type, "type"},
				                        {type list, "list"}, {type record, "record"}, {type table, "table"},
				                        {type function, "function"}, {type anynonnull, "any"}
				                    },
				                    hit = List.First(List.Select(candidates, each Type.Is(t, _{0})), null)
				                in
				                    if Type.Is(t, type none) then "none" else if hit = null then "any" else hit{1},
				            FieldsText = (fields as record, open as logical) as text =>
				                let
				                    names = Record.FieldNames(fields),
				                    parts = List.Transform(names, (n) =>
				                        let f = Record.Field(fields, n) in
				                            (if f[Optional] then "optional " else "") & Ident(n) & " = " & TypeText(f[Type])),
				                    all = if open then parts & {"..."} else parts
				                in
				                    "[" & Text.Combine(all, ", ") & "]",
				            FunctionTypeText = (t as type) as text =>
				                let
				                    params = Type.FunctionParameters(t),
				                    names = Record.FieldNames(params),
				                    required = Type.FunctionRequiredParameters(t),
				                    parts = List.Transform(List.Positions(names), (i) =>
				                        (if i >= required then "optional " else "") & Ident(names{i}) & " as "
				                            & TypeText(Record.Field(params, names{i})))
				                in
				                    "function (" & Text.Combine(parts, ", ") & ") as " & TypeText(Type.FunctionReturn(t)),
				            TypeText = (t as type) as text =>
				                let
				                    nullable = Type.IsNullable(t) and not Type.Is(t, type null),
				                    base = Type.NonNullable(t),
				                    named = TypeName(t),
				                    body =
				                        if Type.Is(t, type null) then "null"
				                        else if named <> null then named
				                        else if Type.Is(base, type table) then
				                            "table " & FieldsText(Type.RecordFields(Type.TableRow(base)), false)
				                        else if Type.Is(base, type record) then
				                            FieldsText(Type.RecordFields(base), Type.IsOpenRecord(base))
				                        // A let binding that calls itself needs @; without it the engine reports
				                        // "The import TypeText matches no exports".
				                        else if Type.Is(base, type list) then "{" & @TypeText(Type.ListItem(base)) & "}"
				                        else if Type.Is(base, type function) then FunctionTypeText(base)
				                        else Primitive(base),
				                    // `any` includes null; the same type without null is spelled anynonnull.
				                    spelled = if body = "any" and not Type.IsNullable(t) then "anynonnull" else body
				                in
				                    (if nullable and body <> "any" then "nullable " else "") & spelled,
				            ErrorText = (e as record) as text =>
				                let
				                    detail = Record.FieldOrDefault(e, "Detail", null),
				                    detailText = if detail = null then "" else " | Detail: " & Safe(() => detail)
				                in
				                    "error: " & OrEmpty(e[Reason]) & ": " & OrEmpty(e[Message]) & detailText,
				            OrEmpty = (x as any) as text => if x is null then "" else Text.From(x),
				            // Every nested value is rendered through Safe with a thunk, so an error in one cell shows
				            // as that cell's text instead of failing the whole case.
				            Safe = (get as function) as text =>
				                let r = try Render(get()) in if r[HasError] then ErrorText(r[Error]) else r[Value],
				            MaxItems = 100,
				            ListText = (items as list) as text =>
				                let
				                    head = List.FirstN(items, MaxItems + 1),
				                    shown = List.FirstN(head, MaxItems),
				                    parts = List.Transform(List.Positions(shown), (i) => Safe(() => shown{i})),
				                    more = if List.Count(head) > MaxItems then {"..."} else {}
				                in
				                    "{" & Text.Combine(parts & more, ", ") & "}",
				            TableText = (t as table) as text =>
				                let
				                    head = Table.FirstN(t, MaxItems + 1),
				                    shown = Table.FirstN(head, MaxItems),
				                    columns = Table.ColumnNames(t),
				                    rows = List.Transform(Table.ToRecords(shown), (r) =>
				                        "{" & Text.Combine(List.Transform(columns, (c) => Safe(() => Record.Field(r, c))), ", ")
				                            & "}"),
				                    more = if Table.RowCount(head) > MaxItems then {"..."} else {}
				                in
				                    "#table(type " & TypeText(Value.Type(t)) & ", {" & Text.Combine(rows & more, ", ") & "})",
				            Render = (v as any) as text =>
				                if v is null then "null"
				                else if v is logical then (if v then "true" else "false")
				                else if v is number then Num(v)
				                else if v is text then Quote(v)
				                else if v is date then
				                    "#date(" & Text.Combine(List.Transform({Date.Year(v), Date.Month(v), Date.Day(v)}, Num), ", ") & ")"
				                else if v is datetimezone then
				                    "#datetimezone(" & Text.Combine(List.Transform({Date.Year(v), Date.Month(v), Date.Day(v),
				                        Time.Hour(v), Time.Minute(v), Time.Second(v),
				                        DateTimeZone.ZoneHours(v), DateTimeZone.ZoneMinutes(v)}, Num), ", ") & ")"
				                else if v is datetime then
				                    "#datetime(" & Text.Combine(List.Transform({Date.Year(v), Date.Month(v), Date.Day(v),
				                        Time.Hour(v), Time.Minute(v), Time.Second(v)}, Num), ", ") & ")"
				                else if v is time then
				                    "#time(" & Text.Combine(List.Transform({Time.Hour(v), Time.Minute(v), Time.Second(v)}, Num), ", ") & ")"
				                else if v is duration then
				                    "#duration(" & Text.Combine(List.Transform({Duration.Days(v), Duration.Hours(v),
				                        Duration.Minutes(v), Duration.Seconds(v)}, Num), ", ") & ")"
				                else if v is binary then
				                    "#binary({" & Text.Combine(List.Transform(Binary.ToList(v), Num), ", ") & "})"
				                else if v is list then ListText(v)
				                else if v is record then
				                    "[" & Text.Combine(List.Transform(Record.FieldNames(v), (f) =>
				                        Ident(f) & " = " & Safe(() => Record.Field(v, f))), ", ") & "]"
				                else if v is table then TableText(v)
				                else if v is type then "type " & TypeText(v)
				                else if v is function then FunctionTypeText(Value.Type(v))
				                else "<" & Primitive(Value.Type(v)) & ">",
				            // Separate Expression.Evaluate calls share cached values: with the same #table literal in
				            // two cases, Table.TransformColumnNames in one made Table.Buffer in the other return the
				            // renamed columns (reproduced 2026-09-29; one query with both steps is not affected). A
				            // distinct environment per case is meant to keep each evaluation to itself.
				            Run = (i as number, code as text) as text =>
				                let r = try Render(Expression.Evaluate(code, Environment & [#"__runner case" = i])) in
				                    if r[HasError] then ErrorText(r[Error]) else r[Value],
				            Result = #table(
				                type table [seq = Int64.Type, id = text, result = text],
				                List.Transform(List.Positions(Cases), (i) => {i, Cases{i}{0}, Run(i, Cases{i}{1})})
				            )
				        in
				            Result,
				    Pages = #table(type table [seq = Int64.Type, Function = text, Description = text, Block = Int64.Type, Code = text, Recorded = text], {{0, "Table.AlternateRows", "Keeps the initial offset then alternates taking and skipping the following rows. - table: The input table. - offset: The number of rows to keep before starting iterations. - skip: The number of rows to remove in each iteration. - take: The number of rows to keep in each iteration.", 1, "Table.AlternateRows(#table({""n""}, {{1}, {2}, {3}, {4}, {5}}), 1, 1, 1)", "#table(type table [n = any], {{1}, {3}, {5}})"}, {1, "Table.Combine", "Returns a table that is the result of merging a list of tables, tables. The resulting table will have a row type structure defined by columns or by a union of the input types if columns is not specified.", 1, "Table.Combine({#table({""a""}, {{1}}), #table({""b""}, {{2}})})", "#table(type table [a = any, b = any], {{1, null}, {null, 2}})"}, {2, "Table.FindText", "Returns the rows in the table table that contain the text text. If the text is not found, an empty table is returned.", 1, "let#(lf)    T = #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}, {""a"", 3}})#(lf)in#(lf)    Table.FindText(T, ""b"")", "#table(type table [Name = text, Qty = Int64.Type], {{""b"", 2}})"}, {3, "Table.First", "Returns the first row of the table or an optional default value, default, if the table is empty.", 1, "let#(lf)    T = #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}, {""a"", 3}})#(lf)in#(lf)    {Table.First(T), Table.First(#table({""a""}, {}))}", "{[Name = ""a"", Qty = 1], null}"}, {4, "Table.FirstN", "Returns the first row(s) of the table table, depending on the value of countOrCondition: - If countOrCondition is a number, that many rows (starting at the top) will be returned. - If countOrCondition is a condition, the rows that meet the condition will be returned until a row does not meet the condition.", 1, "let#(lf)    T = #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}, {""a"", 3}})#(lf)in#(lf)    {Table.FirstN(T, 2), Table.FirstN(T, each [Name] = ""a"")}", "{#table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}}), #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}})}"}, {5, "Table.FirstValue", "Returns the first column of the first row of the table table or a specified default value.", 1, "let#(lf)    T = #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}, {""a"", 3}})#(lf)in#(lf)    Table.FirstValue(T)", """a"""}, {6, "Table.FromPartitions", "Returns a table that is the result of combining a set of partitioned tables, partitions. partitionColumn is the name of the column to add. The type of the column defaults to any, but can be specified by partitionColumnType.", 1, "Table.FromPartitions(""Year"", {{2023, #table({""v""}, {{1}})}, {2024, #table({""v""}, {{2}})}}, Int64.Type)", "#table(type table [v = any, Year = Int64.Type], {{1, 2023}, {2, 2024}})"}, {7, "Table.InsertRows", "Returns a table with the list of rows, rows, inserted into the table at the given position, offset. Each column in the row to insert must match the column types of the table.", 1, "let#(lf)    T = #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}, {""a"", 3}})#(lf)in#(lf)    Table.InsertRows(T, 1, {[Name = ""z"", Qty = 9]})", "#table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""z"", 9}, {""b"", 2}, {""a"", 3}})"}, {8, "Table.Last", "Returns the last row of the table or an optional default value, default, if the table is empty.", 1, "let#(lf)    T = #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}, {""a"", 3}})#(lf)in#(lf)    Table.Last(T)", "[Name = ""a"", Qty = 3]"}, {9, "Table.LastN", "Returns the last row(s) from the table, table, depending on the value of countOrCondition: - If countOrCondition is a number, that many rows will be returned starting from position (end - countOrCondition). - If countOrCondition is a condition, the rows that meet the condition will be returned in ascending position until a row does not meet the condition.", 1, "let#(lf)    T = #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}, {""a"", 3}})#(lf)in#(lf)    Table.LastN(T, 2)", "#table(type table [Name = text, Qty = Int64.Type], {{""b"", 2}, {""a"", 3}})"}, {10, "Table.MatchesAllRows", "Indicates whether all the rows in the table match the given condition. Returns true if all of the rows match, false otherwise.", 1, "let#(lf)    T = #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}, {""a"", 3}})#(lf)in#(lf)    Table.MatchesAllRows(T, each [Qty] > 0)", "true"}, {11, "Table.MatchesAnyRows", "Indicates whether any the rows in the table match the given condition. Returns true if any of the rows match, false otherwise.", 1, "let#(lf)    T = #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}, {""a"", 3}})#(lf)in#(lf)    Table.MatchesAnyRows(T, each [Qty] > 2)", "true"}, {12, "Table.Partition", "Partitions the table into a list of groups number of tables, based on the value of the column and a hash function. The hash function is applied to the value of the column row to obtain a hash value for the row. The hash value modulo groups determines in which of the returned tables the row will be placed. - table: The table to partition. - column: The column to hash to determine which returned table the row is in. - groups: The number of tables the input table will be partitioned into. - hash: The function applied to obtain a hash value.", 1, "Table.Partition(#table({""n""}, {{1}, {2}, {3}, {4}}), ""n"", 2, each _)", "{#table(type table [n = any], {{2}, {4}}), #table(type table [n = any], {{1}, {3}})}"}, {13, "Table.Range", "Returns the rows from the table starting at the specified offset. An optional parameter, count, specifies how many rows to return. By default, all the rows after the offset are returned.", 1, "let#(lf)    T = #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}, {""a"", 3}})#(lf)in#(lf)    Table.Range(T, 1, 1)", "#table(type table [Name = text, Qty = Int64.Type], {{""b"", 2}})"}, {14, "Table.RemoveFirstN", "Returns a table that does not contain the first specified number of rows, countOrCondition, of the table table. The number of rows removed depends on the optional parameter countOrCondition. - If countOrCondition is omitted only the first row is removed. - If countOrCondition is a number, that many rows (starting at the top) will be removed. - If countOrCondition is a condition, the rows that meet the condition will be removed until a row does not meet the condition.", 1, "let#(lf)    T = #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}, {""a"", 3}})#(lf)in#(lf)    Table.RemoveFirstN(T, 1)", "#table(type table [Name = text, Qty = Int64.Type], {{""b"", 2}, {""a"", 3}})"}, {15, "Table.RemoveLastN", "Returns a table that does not contain the last countOrCondition rows of the table table. The number of rows removed depends on the optional parameter countOrCondition. - If countOrCondition is omitted only the last row is removed. - If countOrCondition is a number, that many rows (starting at the bottom) will be removed. - If countOrCondition is a condition, the rows that meet the condition will be removed until a row does not meet the condition.", 1, "let#(lf)    T = #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}, {""a"", 3}})#(lf)in#(lf)    Table.RemoveLastN(T, 1)", "#table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}})"}, {16, "Table.RemoveRows", "Removes count of rows from the beginning of the table, starting at the offset specified. A default count of 1 is used if the count parameter isn't provided.", 1, "let#(lf)    T = #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}, {""a"", 3}})#(lf)in#(lf)    Table.RemoveRows(T, 0, 2)", "#table(type table [Name = text, Qty = Int64.Type], {{""a"", 3}})"}, {17, "Table.RemoveRowsWithErrors", "Returns a table with the rows removed from the input table that contain an error in at least one of the cells. If a columns list is specified, then only the cells in the specified columns are inspected for errors.", 1, "Table.RemoveRowsWithErrors(Table.TransformColumnTypes(#table({""v""}, {{""1""}, {""x""}}), {{""v"", Int64.Type}}))", "#table(type table [v = nullable number], {{1}})"}, {18, "Table.Repeat", "Returns a table with the rows from the input table repeated the specified count times.", 1, "Table.Repeat(#table({""a""}, {{1}}), 3)", "#table(type table [a = any], {{1}, {1}, {1}})"}, {19, "Table.ReplaceRows", "Replaces a specified number of rows, count, in the input table with the specified rows, beginning after the offset. The rows parameter is a list of records. - table: The table where the replacement is performed. - offset: The number of rows to skip before making the replacement. - count: The number of rows to replace. - rows: The list of row records to insert into the table at the location specified by the offset.", 1, "let#(lf)    T = #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}, {""a"", 3}})#(lf)in#(lf)    Table.ReplaceRows(T, 0, 1, {[Name = ""z"", Qty = 0]})", "#table(type table [Name = text, Qty = Int64.Type], {{""z"", 0}, {""b"", 2}, {""a"", 3}})"}, {20, "Table.ReverseRows", "Returns a table with the rows from the input table in reverse order.", 1, "let#(lf)    T = #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}, {""a"", 3}})#(lf)in#(lf)    Table.ReverseRows(T)", "#table(type table [Name = text, Qty = Int64.Type], {{""a"", 3}, {""b"", 2}, {""a"", 1}})"}, {21, "Table.SelectRows", "Returns a table of rows from the table, that matches the selection condition.", 1, "let#(lf)    T = #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}, {""a"", 3}})#(lf)in#(lf)    Table.SelectRows(T, each [Qty] >= 2)", "#table(type table [Name = text, Qty = Int64.Type], {{""b"", 2}, {""a"", 3}})"}, {22, "Table.SelectRowsWithErrors", "Returns a table with only those rows of the input table that contain an error in at least one of the cells. If a columns list is specified, then only the cells in the specified columns are inspected for errors.", 1, "Table.SelectRowsWithErrors(Table.TransformColumnTypes(#table({""v""}, {{""1""}, {""x""}}), {{""v"", Int64.Type}}))", "#table(type table [v = nullable number], {{error: DataFormat.Error: We couldn't convert to Number. | Detail: ""x""}})"}, {23, "Table.SingleRow", "Returns the single row in the one row table. If the table has more than one row, an error is raised.", 1, "let#(lf)    T = #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}, {""a"", 3}})#(lf)in#(lf)    {Table.SingleRow(#table({""a""}, {{1}})), Table.SingleRow(T)}", "{[a = 1], error: Expression.Error: There were too many elements in the enumeration to complete the operation. | Detail: {[Name = ""a"", Qty = 1], [Name = ""b"", Qty = 2], [Name = ""a"", Qty = 3]}}"}, {24, "Table.Skip", "Returns a table that does not contain the first specified number of rows, countOrCondition, of the table table. The number of rows skipped depends on the optional parameter countOrCondition. - If countOrCondition is omitted only the first row is skipped. - If countOrCondition is a number, that many rows (starting at the top) will be skipped. - If countOrCondition is a condition, the rows that meet the condition will be skipped until a row does not meet the condition.", 1, "let#(lf)    T = #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}, {""a"", 3}})#(lf)in#(lf)    Table.Skip(T, 1)", "#table(type table [Name = text, Qty = Int64.Type], {{""b"", 2}, {""a"", 3}})"}, {25, "Table.SplitAt", "Returns a list containing two tables: a table with the first N rows of table (as specified by count) and a table containing the remaining rows of table. If the tables of the resulting list are enumerated exactly once and in order, the function will enumerate table only once.", 1, "let#(lf)    T = #table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}, {""b"", 2}, {""a"", 3}})#(lf)in#(lf)    Table.SplitAt(T, 1)", "{#table(type table [Name = text, Qty = Int64.Type], {{""a"", 1}}), #table(type table [Name = text, Qty = Int64.Type], {{""b"", 2}, {""a"", 3}})}"}}),
				    Joined = Table.NestedJoin(Pages, "seq", Table.TransformColumns(Live, {{"id", Number.From}}), "id", "L", JoinKind.LeftOuter),
				    Expanded = Table.ExpandTableColumn(Joined, "L", {"result"}, {"Live"}),
				    Matched = Table.AddColumn(Expanded, "Match", each if [Live] = [Recorded] then "yes" else "NO", type text),
				    Sorted = Table.Sort(Matched, {{"seq", Order.Ascending}})
				in
				    Sorted

	annotation PBI_ResultType = Table
