/// Generated by lab/review/build_review.py from the example pages. Do not edit.
table TextTransformations
	lineageTag: afd5202f-7942-5508-b97a-91275cbb68ca

	column seq
		dataType: int64
		lineageTag: fcded0ac-6ff6-5f58-a845-ce03b1d0a198
		summarizeBy: none
		sourceColumn: seq

	column Function
		dataType: string
		lineageTag: 169fed08-72e7-5fd5-a218-caf480b60ccd
		summarizeBy: none
		sourceColumn: Function

	column Block
		dataType: int64
		lineageTag: e5ab4f85-1f9b-5ee4-bf3f-7055153c55f0
		summarizeBy: none
		sourceColumn: Block

	column Code
		dataType: string
		lineageTag: 6c44340d-ac91-59b8-bf13-9368f16d2037
		summarizeBy: none
		sourceColumn: Code

	column Recorded
		dataType: string
		lineageTag: 3d751edf-64af-58dc-9389-358205046e4a
		summarizeBy: none
		sourceColumn: Recorded

	column Live
		dataType: string
		lineageTag: 8000d383-52d7-5766-99b4-dc056537128f
		summarizeBy: none
		sourceColumn: Live

	column Match
		dataType: string
		lineageTag: 9b786968-1597-5493-8c5b-28242a50939b
		summarizeBy: none
		sourceColumn: Match

	measure Examples = COUNTROWS('TextTransformations')
		formatString: 0
		lineageTag: d82b7f9e-16e7-552a-a93c-115df7bb560b

	partition TextTransformations = m
		mode: import
		source =
				let
				    Live = 
				        // runner.pq - evaluates every ```m block of the skills in the engine and renders each result
				        // as M literal text, so a page can quote what the engine returned instead of what we expect.
				        //
				        // run_examples.py replaces the Cases line with the blocks it collected and builds a PBIP
				        // whose only partition is this query. It also replaces the Allowed line with the names
				        // m_blocks.allowed_names lets a block use, and each case is evaluated with Expression.Evaluate
				        // over those members of #shared only: no data sources, no connectors, no other queries, no
				        // Expression.Evaluate - even for a name m_blocks.unsafe_calls could not see.
				        let
				            Cases = {{"0", "{Text.AfterDelimiter(""111-222-333"", ""-""), Text.AfterDelimiter(""111-222-333"", ""-"", {0, RelativePosition.FromEnd})}"}, {"1", "Text.BeforeDelimiter(""111-222-333"", ""-"", 1)"}, {"2", "Text.BetweenDelimiters(""a (b) c (d)"", ""("", "")"", 1)"}, {"3", "Text.Clean(""a#(#)(lf)b#(#)(tab)c"")"}, {"4", "Text.Combine({""a"", null, ""b""}, "", "")"}, {"5", "Text.Lower(""ÀBC"")"}, {"6", "Text.PadEnd(""7"", 3, ""."")"}, {"7", "{Text.PadStart(""7"", 3, ""0""), Text.PadStart(""1234"", 3, ""0"")}"}, {"8", "Text.Proper(""mcDONALD o'brien"")"}, {"9", "Text.Repeat(""ab"", 3)"}, {"10", "Text.Reverse(""abc"")"}, {"11", "Text.Split(""a,,b"", "","")"}, {"12", "Text.SplitAny(""a,b;c"", "",;"")"}, {"13", "{Text.Trim(""  a  ""), Text.Trim(""--a--"", ""-"")}"}, {"14", "Text.TrimEnd(""a000"", ""0"")"}, {"15", "Text.TrimStart(""000123"", ""0"")"}, {"16", "{Text.Upper(""abc""), Text.Upper(""straße"")}"}},
				            Allowed = {"AccessControlEntry.ConditionContextType", "AccessControlEntry.Type", "AccessControlKind.Allow", "AccessControlKind.Deny", "AccessControlKind.Type", "Any.Type", "Binary.ApproximateLength", "Binary.Buffer", "Binary.Combine", "Binary.Compress", "Binary.Decompress", "Binary.From", "Binary.FromList", "Binary.FromText", "Binary.InferContentType", "Binary.Length", "Binary.Range", "Binary.Split", "Binary.ToList", "Binary.ToText", "Binary.Type", "Binary.View", "Binary.ViewError", "Binary.ViewFunction", "BinaryEncoding.Base64", "BinaryEncoding.Hex", "BinaryEncoding.Type", "BinaryFormat.7BitEncodedSignedInteger", "BinaryFormat.7BitEncodedUnsignedInteger", "BinaryFormat.Binary", "BinaryFormat.Byte", "BinaryFormat.ByteOrder", "BinaryFormat.Choice", "BinaryFormat.Decimal", "BinaryFormat.Double", "BinaryFormat.Group", "BinaryFormat.Length", "BinaryFormat.List", "BinaryFormat.Null", "BinaryFormat.Record", "BinaryFormat.SignedInteger16", "BinaryFormat.SignedInteger32", "BinaryFormat.SignedInteger64", "BinaryFormat.Single", "BinaryFormat.Text", "BinaryFormat.Transform", "BinaryFormat.UnsignedInteger16", "BinaryFormat.UnsignedInteger32", "BinaryFormat.UnsignedInteger64", "BinaryOccurrence.Optional", "BinaryOccurrence.Repeating", "BinaryOccurrence.Required", "BinaryOccurrence.Type", "BufferMode.Delayed", "BufferMode.Eager", "BufferMode.Type", "Byte.From", "Byte.Type", "ByteOrder.BigEndian", "ByteOrder.LittleEndian", "ByteOrder.Type", "Certificate.Type", "Character.FromNumber", "Character.ToNumber", "Character.Type", "Combiner.CombineTextByDelimiter", "Combiner.CombineTextByEachDelimiter", "Combiner.CombineTextByLengths", "Combiner.CombineTextByPositions", "Combiner.CombineTextByRanges", "Comparer.Equals", "Comparer.FromCulture", "Comparer.Ordinal", "Comparer.OrdinalIgnoreCase", "Compression.Brotli", "Compression.Deflate", "Compression.GZip", "Compression.LZ4", "Compression.None", "Compression.Snappy", "Compression.Type", "Compression.Zstandard", "Csv.Document", "CsvStyle.QuoteAfterDelimiter", "CsvStyle.QuoteAlways", "CsvStyle.Type", "Currency.From", "Currency.Type", "Date.AddDays", "Date.AddMonths", "Date.AddQuarters", "Date.AddWeeks", "Date.AddYears", "Date.Day", "Date.DayOfWeek", "Date.DayOfWeekName", "Date.DayOfYear", "Date.DaysInMonth", "Date.EndOfDay", "Date.EndOfMonth", "Date.EndOfQuarter", "Date.EndOfWeek", "Date.EndOfYear", "Date.From", "Date.FromText", "Date.IsInCurrentDay", "Date.IsInCurrentMonth", "Date.IsInCurrentQuarter", "Date.IsInCurrentWeek", "Date.IsInCurrentYear", "Date.IsInNextDay", "Date.IsInNextMonth", "Date.IsInNextNDays", "Date.IsInNextNMonths", "Date.IsInNextNQuarters", "Date.IsInNextNWeeks", "Date.IsInNextNYears", "Date.IsInNextQuarter", "Date.IsInNextWeek", "Date.IsInNextYear", "Date.IsInPreviousDay", "Date.IsInPreviousMonth", "Date.IsInPreviousNDays", "Date.IsInPreviousNMonths", "Date.IsInPreviousNQuarters", "Date.IsInPreviousNWeeks", "Date.IsInPreviousNYears", "Date.IsInPreviousQuarter", "Date.IsInPreviousWeek", "Date.IsInPreviousYear", "Date.IsInYearToDate", "Date.IsLeapYear", "Date.Month", "Date.MonthName", "Date.QuarterOfYear", "Date.StartOfDay", "Date.StartOfMonth", "Date.StartOfQuarter", "Date.StartOfWeek", "Date.StartOfYear", "Date.ToRecord", "Date.ToText", "Date.Type", "Date.WeekOfMonth", "Date.WeekOfYear", "Date.Year", "DateTime.AddZone", "DateTime.Date", "DateTime.From", "DateTime.FromFileTime", "DateTime.FromText", "DateTime.IsInCurrentHour", "DateTime.IsInCurrentMinute", "DateTime.IsInCurrentSecond", "DateTime.IsInNextHour", "DateTime.IsInNextMinute", "DateTime.IsInNextNHours", "DateTime.IsInNextNMinutes", "DateTime.IsInNextNSeconds", "DateTime.IsInNextSecond", "DateTime.IsInPreviousHour", "DateTime.IsInPreviousMinute", "DateTime.IsInPreviousNHours", "DateTime.IsInPreviousNMinutes", "DateTime.IsInPreviousNSeconds", "DateTime.IsInPreviousSecond", "DateTime.Time", "DateTime.ToRecord", "DateTime.ToText", "DateTime.Type", "DateTimeZone.From", "DateTimeZone.FromFileTime", "DateTimeZone.FromText", "DateTimeZone.RemoveZone", "DateTimeZone.SwitchZone", "DateTimeZone.ToRecord", "DateTimeZone.ToText", "DateTimeZone.ToUtc", "DateTimeZone.Type", "DateTimeZone.ZoneHours", "DateTimeZone.ZoneMinutes", "Day.Friday", "Day.Monday", "Day.Saturday", "Day.Sunday", "Day.Thursday", "Day.Tuesday", "Day.Type", "Day.Wednesday", "Decimal.From", "Decimal.Type", "Double.From", "Double.Type", "Duration.Days", "Duration.From", "Duration.FromText", "Duration.Hours", "Duration.Minutes", "Duration.Seconds", "Duration.ToRecord", "Duration.ToText", "Duration.TotalDays", "Duration.TotalHours", "Duration.TotalMinutes", "Duration.TotalSeconds", "Duration.Type", "EmigoDataSourceConnector.NavigationFunctionType", "Error.Record", "Excel.RichDocument", "Expression.Constant", "Expression.Identifier", "ExtraValues.Error", "ExtraValues.Ignore", "ExtraValues.List", "ExtraValues.Type", "Function.From", "Function.Invoke", "Function.IsDataSource", "Function.ScalarVector", "Function.Type", "Geography.FromWellKnownText", "Geography.ToWellKnownText", "GeographyPoint.From", "Geometry.FromWellKnownText", "Geometry.ToWellKnownText", "GeometryPoint.From", "GroupKind.Global", "GroupKind.Local", "GroupKind.Type", "Guid.From", "Guid.Type", "HiveProtocol.HTTP", "HiveProtocol.Standard", "HiveProtocol.Type", "Identity.Type", "IdentityProvider.Type", "Int16.From", "Int16.Type", "Int32.From", "Int32.Type", "Int64.From", "Int64.Type", "Int8.From", "Int8.Type", "ItemExpression.From", "ItemExpression.Item", "JoinAlgorithm.Dynamic", "JoinAlgorithm.LeftHash", "JoinAlgorithm.LeftIndex", "JoinAlgorithm.PairwiseHash", "JoinAlgorithm.RightHash", "JoinAlgorithm.RightIndex", "JoinAlgorithm.SortMerge", "JoinAlgorithm.Type", "JoinKind.FullOuter", "JoinKind.Inner", "JoinKind.LeftAnti", "JoinKind.LeftOuter", "JoinKind.LeftSemi", "JoinKind.RightAnti", "JoinKind.RightOuter", "JoinKind.RightSemi", "JoinKind.Type", "JoinSide.Left", "JoinSide.Right", "JoinSide.Type", "Json.Document", "Json.FromValue", "LimitClauseKind.AnsiSql2008", "LimitClauseKind.Limit", "LimitClauseKind.LimitOffset", "LimitClauseKind.None", "LimitClauseKind.Top", "LimitClauseKind.Type", "Lines.FromBinary", "Lines.FromText", "Lines.ToBinary", "Lines.ToText", "List.Accumulate", "List.AllTrue", "List.Alternate", "List.AnyTrue", "List.Average", "List.Buffer", "List.Combine", "List.ConformToPageReader", "List.Contains", "List.ContainsAll", "List.ContainsAny", "List.Count", "List.Covariance", "List.DateTimeZones", "List.DateTimes", "List.Dates", "List.Difference", "List.Distinct", "List.Durations", "List.FindText", "List.First", "List.FirstN", "List.Generate", "List.InsertRange", "List.Intersect", "List.IsDistinct", "List.IsEmpty", "List.Last", "List.LastN", "List.MatchesAll", "List.MatchesAny", "List.Max", "List.MaxN", "List.Median", "List.Min", "List.MinN", "List.Mode", "List.Modes", "List.NonNullCount", "List.Numbers", "List.Percentile", "List.PositionOf", "List.PositionOfAny", "List.Positions", "List.Product", "List.Random", "List.Range", "List.RemoveFirstN", "List.RemoveItems", "List.RemoveLastN", "List.RemoveMatchingItems", "List.RemoveNulls", "List.RemoveRange", "List.Repeat", "List.ReplaceMatchingItems", "List.ReplaceRange", "List.ReplaceValue", "List.Reverse", "List.Select", "List.Single", "List.SingleOrDefault", "List.Skip", "List.Sort", "List.Split", "List.StandardDeviation", "List.Sum", "List.Times", "List.Transform", "List.TransformMany", "List.Type", "List.Union", "List.Zip", "Logical.From", "Logical.FromText", "Logical.ToText", "Logical.Type", "MissingField.Error", "MissingField.Ignore", "MissingField.Type", "MissingField.UseNull", "None.Type", "Null.Type", "Number.Abs", "Number.Acos", "Number.Asin", "Number.Atan", "Number.Atan2", "Number.BitwiseAnd", "Number.BitwiseNot", "Number.BitwiseOr", "Number.BitwiseShiftLeft", "Number.BitwiseShiftRight", "Number.BitwiseXor", "Number.Combinations", "Number.Cos", "Number.Cosh", "Number.E", "Number.Epsilon", "Number.Exp", "Number.Factorial", "Number.From", "Number.FromText", "Number.IntegerDivide", "Number.IsEven", "Number.IsNaN", "Number.IsOdd", "Number.Ln", "Number.Log", "Number.Log10", "Number.Mod", "Number.NaN", "Number.NegativeInfinity", "Number.PI", "Number.Permutations", "Number.PositiveInfinity", "Number.Power", "Number.Random", "Number.RandomBetween", "Number.Round", "Number.RoundAwayFromZero", "Number.RoundDown", "Number.RoundTowardZero", "Number.RoundUp", "Number.Sign", "Number.Sin", "Number.Sinh", "Number.Sqrt", "Number.Tan", "Number.Tanh", "Number.ToText", "Number.Type", "ODataOmitValues.Nulls", "ODataOmitValues.Type", "Occurrence.All", "Occurrence.First", "Occurrence.Last", "Occurrence.Optional", "Occurrence.Repeating", "Occurrence.Required", "Occurrence.Type", "Office.InferChartPropertiesGenerator", "Order.Ascending", "Order.Descending", "Order.Type", "Password.Type", "Percentage.From", "Percentage.Type", "PercentileMode.ExcelExc", "PercentileMode.ExcelInc", "PercentileMode.SqlCont", "PercentileMode.SqlDisc", "PercentileMode.Type", "PowerPoint.Presentation", "Precision.Decimal", "Precision.Double", "Precision.Type", "QuoteStyle.Csv", "QuoteStyle.None", "QuoteStyle.Type", "RankKind.Competition", "RankKind.Dense", "RankKind.Ordinal", "RankKind.Type", "Record.AddField", "Record.Combine", "Record.Field", "Record.FieldCount", "Record.FieldNames", "Record.FieldOrDefault", "Record.FieldValues", "Record.FromList", "Record.FromTable", "Record.HasFields", "Record.RemoveFields", "Record.RenameFields", "Record.ReorderFields", "Record.SelectFields", "Record.ToList", "Record.ToTable", "Record.TransformFields", "Record.Type", "RelativePosition.FromEnd", "RelativePosition.FromStart", "RelativePosition.Type", "Replacer.ReplaceText", "Replacer.ReplaceValue", "RoundingMode.AwayFromZero", "RoundingMode.Down", "RoundingMode.ToEven", "RoundingMode.TowardZero", "RoundingMode.Type", "RoundingMode.Up", "RowExpression.Column", "RowExpression.From", "RowExpression.Row", "SapBusinessWarehouseExecutionMode.BasXml", "SapBusinessWarehouseExecutionMode.BasXmlGzip", "SapBusinessWarehouseExecutionMode.DataStream", "SapBusinessWarehouseExecutionMode.Type", "SapHanaDistribution.All", "SapHanaDistribution.Connection", "SapHanaDistribution.Off", "SapHanaDistribution.Statement", "SapHanaDistribution.Type", "SapHanaRangeOperator.Equals", "SapHanaRangeOperator.GreaterThan", "SapHanaRangeOperator.GreaterThanOrEquals", "SapHanaRangeOperator.LessThan", "SapHanaRangeOperator.LessThanOrEquals", "SapHanaRangeOperator.NotEquals", "SapHanaRangeOperator.Type", "Single.From", "Single.Type", "SparkProtocol.Azure", "SparkProtocol.HTTP", "SparkProtocol.Standard", "SparkProtocol.Type", "Splitter.SplitByNothing", "Splitter.SplitTextByAnyDelimiter", "Splitter.SplitTextByCharacterTransition", "Splitter.SplitTextByDelimiter", "Splitter.SplitTextByEachDelimiter", "Splitter.SplitTextByLengths", "Splitter.SplitTextByPositions", "Splitter.SplitTextByRanges", "Splitter.SplitTextByRepeatedLengths", "Splitter.SplitTextByWhitespace", "Table.AddColumn", "Table.AddFuzzyClusterColumn", "Table.AddIndexColumn", "Table.AddJoinColumn", "Table.AddKey", "Table.AddRankColumn", "Table.AggregateTableColumn", "Table.AlternateRows", "Table.ApproximateRowCount", "Table.Buffer", "Table.ClearDown", "Table.Column", "Table.ColumnCount", "Table.ColumnNames", "Table.ColumnsOfType", "Table.Combine", "Table.CombineColumns", "Table.CombineColumnsToRecord", "Table.ConformToPageReader", "Table.Contains", "Table.ContainsAll", "Table.ContainsAny", "Table.DemoteHeaders", "Table.Distinct", "Table.DuplicateColumn", "Table.ExpandListColumn", "Table.ExpandRecordColumn", "Table.ExpandTableColumn", "Table.FillDown", "Table.FillUp", "Table.FindText", "Table.First", "Table.FirstN", "Table.FirstValue", "Table.FromColumns", "Table.FromList", "Table.FromPartitions", "Table.FromRecords", "Table.FromRows", "Table.FromValue", "Table.FuzzyGroup", "Table.FuzzyJoin", "Table.FuzzyNestedJoin", "Table.Group", "Table.HasColumns", "Table.InsertRows", "Table.IsDistinct", "Table.IsEmpty", "Table.Join", "Table.Keys", "Table.Last", "Table.LastN", "Table.MatchesAllRows", "Table.MatchesAnyRows", "Table.Max", "Table.MaxN", "Table.Min", "Table.MinN", "Table.NestedJoin", "Table.Partition", "Table.PartitionKey", "Table.PartitionValues", "Table.Pivot", "Table.PositionOf", "Table.PositionOfAny", "Table.PrefixColumns", "Table.Profile", "Table.PromoteHeaders", "Table.Range", "Table.RemoveColumns", "Table.RemoveFirstN", "Table.RemoveLastN", "Table.RemoveMatchingRows", "Table.RemoveRows", "Table.RemoveRowsWithErrors", "Table.RenameColumns", "Table.ReorderColumns", "Table.Repeat", "Table.ReplaceErrorValues", "Table.ReplaceKeys", "Table.ReplaceMatchingRows", "Table.ReplacePartitionKey", "Table.ReplaceRelationshipIdentity", "Table.ReplaceRows", "Table.ReplaceValue", "Table.ReverseRows", "Table.RowCount", "Table.Schema", "Table.SelectColumns", "Table.SelectRows", "Table.SelectRowsWithErrors", "Table.SingleRow", "Table.Skip", "Table.Sort", "Table.Split", "Table.SplitAt", "Table.SplitColumn", "Table.StopFolding", "Table.ToColumns", "Table.ToList", "Table.ToRecords", "Table.ToRows", "Table.TransformColumnNames", "Table.TransformColumnTypes", "Table.TransformColumns", "Table.TransformRows", "Table.Transpose", "Table.Type", "Table.Unpivot", "Table.UnpivotOtherColumns", "Table.View", "Table.ViewError", "Table.ViewFunction", "Table.WithErrorContext", "Tables.GetRelationships", "Text.AfterDelimiter", "Text.At", "Text.BeforeDelimiter", "Text.BetweenDelimiters", "Text.Clean", "Text.Combine", "Text.Contains", "Text.End", "Text.EndsWith", "Text.Format", "Text.From", "Text.FromBinary", "Text.InferNumberType", "Text.Insert", "Text.Length", "Text.Lower", "Text.Middle", "Text.NewGuid", "Text.PadEnd", "Text.PadStart", "Text.PositionOf", "Text.PositionOfAny", "Text.Proper", "Text.Range", "Text.Remove", "Text.RemoveRange", "Text.Repeat", "Text.Replace", "Text.ReplaceRange", "Text.Reverse", "Text.Select", "Text.Split", "Text.SplitAny", "Text.Start", "Text.StartsWith", "Text.ToBinary", "Text.ToList", "Text.Trim", "Text.TrimEnd", "Text.TrimStart", "Text.Type", "Text.Upper", "TextEncoding.Ascii", "TextEncoding.BigEndianUnicode", "TextEncoding.Type", "TextEncoding.Unicode", "TextEncoding.Utf16", "TextEncoding.Utf8", "TextEncoding.Windows", "Time.EndOfHour", "Time.From", "Time.FromText", "Time.Hour", "Time.Minute", "Time.Second", "Time.StartOfHour", "Time.ToRecord", "Time.ToText", "Time.Type", "TraceLevel.Critical", "TraceLevel.Error", "TraceLevel.Information", "TraceLevel.Type", "TraceLevel.Verbose", "TraceLevel.Warning", "Type.AddTableKey", "Type.ClosedRecord", "Type.Facets", "Type.ForFunction", "Type.ForRecord", "Type.FunctionParameters", "Type.FunctionRequiredParameters", "Type.FunctionReturn", "Type.Is", "Type.IsNullable", "Type.IsOpenRecord", "Type.ListItem", "Type.NonNullable", "Type.OpenRecord", "Type.RecordFields", "Type.ReplaceFacets", "Type.ReplaceTableKeys", "Type.ReplaceTablePartitionKey", "Type.TableColumn", "Type.TableKeys", "Type.TablePartitionKey", "Type.TableRow", "Type.TableSchema", "Type.Type", "Type.Union", "Uri.BuildQueryString", "Uri.Combine", "Uri.EscapeDataString", "Uri.Parts", "Uri.Type", "Value.Add", "Value.As", "Value.Compare", "Value.Divide", "Value.Equals", "Value.Expression", "Value.FromText", "Value.Is", "Value.Metadata", "Value.Multiply", "Value.NullableEquals", "Value.RemoveMetadata", "Value.ReplaceMetadata", "Value.ReplaceType", "Value.Subtract", "Value.Type", "WebMethod.Delete", "WebMethod.Get", "WebMethod.Head", "WebMethod.Patch", "WebMethod.Post", "WebMethod.Put", "WebMethod.Type", "Xml.Document", "Xml.Tables"},
				            Environment = Record.SelectFields(#shared, Allowed, MissingField.Ignore),
				            // A text as an M text literal: "#(" first, so the escapes added after it stay single.
				            Quote = (t as text) as text =>
				                let
				                    s1 = Text.Replace(t, "#(#)(", "#(#)(#)("),
				                    s2 = Text.Replace(s1, """", """"""),
				                    s3 = Text.Replace(s2, "#(cr)", "#(#)(cr)"),
				                    s4 = Text.Replace(s3, "#(lf)", "#(#)(lf)"),
				                    s5 = Text.Replace(s4, "#(tab)", "#(#)(tab)")
				                in
				                    """" & s5 & """",
				            Keywords = {"and", "as", "each", "else", "error", "false", "if", "in", "is", "let", "meta",
				                "not", "null", "or", "otherwise", "section", "shared", "then", "true", "try", "type"},
				            IdentChars = {"A".."Z", "a".."z", "0".."9", "_"},
				            Ident = (name as text) as text =>
				                if name <> "" and Text.Select(name, IdentChars) = name
				                    and not List.Contains({"0".."9"}, Text.Start(name, 1))
				                    and not List.Contains(Keywords, name)
				                then name
				                else "#" & Quote(name),
				            Num = (n as number) as text =>
				                if Number.IsNaN(n) then "#nan"
				                else if n = Number.PositiveInfinity then "#infinity"
				                else if n = Number.NegativeInfinity then "-#infinity"
				                else try Number.ToText(n, "R", "en-US") otherwise Number.ToText(n, null, "en-US"),
				            // Int64.Type, Currency.Type and friends are `number` with no facets set: what names them
				            // is Documentation.Name in their metadata. Printed only when #shared has that name, so a
				            // result can never show a type name the library does not export.
				            TypeName = (t as type) as nullable text =>
				                let
				                    n = Record.FieldOrDefault(Value.Metadata(t), "Documentation.Name", null)
				                in
				                    if n is text and Text.EndsWith(n, ".Type") and Record.HasFields(#shared, n)
				                    then n else null,
				            Primitive = (t as type) as text =>
				                let
				                    candidates = {
				                        {type logical, "logical"}, {type number, "number"}, {type time, "time"},
				                        {type date, "date"}, {type datetime, "datetime"},
				                        {type datetimezone, "datetimezone"}, {type duration, "duration"},
				                        {type text, "text"}, {type binary, "binary"}, {type type, "type"},
				                        {type list, "list"}, {type record, "record"}, {type table, "table"},
				                        {type function, "function"}, {type anynonnull, "any"}
				                    },
				                    hit = List.First(List.Select(candidates, each Type.Is(t, _{0})), null)
				                in
				                    if Type.Is(t, type none) then "none" else if hit = null then "any" else hit{1},
				            FieldsText = (fields as record, open as logical) as text =>
				                let
				                    names = Record.FieldNames(fields),
				                    parts = List.Transform(names, (n) =>
				                        let f = Record.Field(fields, n) in
				                            (if f[Optional] then "optional " else "") & Ident(n) & " = " & TypeText(f[Type])),
				                    all = if open then parts & {"..."} else parts
				                in
				                    "[" & Text.Combine(all, ", ") & "]",
				            FunctionTypeText = (t as type) as text =>
				                let
				                    params = Type.FunctionParameters(t),
				                    names = Record.FieldNames(params),
				                    required = Type.FunctionRequiredParameters(t),
				                    parts = List.Transform(List.Positions(names), (i) =>
				                        (if i >= required then "optional " else "") & Ident(names{i}) & " as "
				                            & TypeText(Record.Field(params, names{i})))
				                in
				                    "function (" & Text.Combine(parts, ", ") & ") as " & TypeText(Type.FunctionReturn(t)),
				            TypeText = (t as type) as text =>
				                let
				                    nullable = Type.IsNullable(t) and not Type.Is(t, type null),
				                    base = Type.NonNullable(t),
				                    named = TypeName(t),
				                    body =
				                        if Type.Is(t, type null) then "null"
				                        else if named <> null then named
				                        else if Type.Is(base, type table) then
				                            "table " & FieldsText(Type.RecordFields(Type.TableRow(base)), false)
				                        else if Type.Is(base, type record) then
				                            FieldsText(Type.RecordFields(base), Type.IsOpenRecord(base))
				                        // A let binding that calls itself needs @; without it the engine reports
				                        // "The import TypeText matches no exports".
				                        else if Type.Is(base, type list) then "{" & @TypeText(Type.ListItem(base)) & "}"
				                        else if Type.Is(base, type function) then FunctionTypeText(base)
				                        else Primitive(base),
				                    // `any` includes null; the same type without null is spelled anynonnull.
				                    spelled = if body = "any" and not Type.IsNullable(t) then "anynonnull" else body
				                in
				                    (if nullable and body <> "any" then "nullable " else "") & spelled,
				            ErrorText = (e as record) as text =>
				                let
				                    detail = Record.FieldOrDefault(e, "Detail", null),
				                    detailText = if detail = null then "" else " | Detail: " & Safe(() => detail)
				                in
				                    "error: " & OrEmpty(e[Reason]) & ": " & OrEmpty(e[Message]) & detailText,
				            OrEmpty = (x as any) as text => if x is null then "" else Text.From(x),
				            // Every nested value is rendered through Safe with a thunk, so an error in one cell shows
				            // as that cell's text instead of failing the whole case.
				            Safe = (get as function) as text =>
				                let r = try Render(get()) in if r[HasError] then ErrorText(r[Error]) else r[Value],
				            MaxItems = 100,
				            ListText = (items as list) as text =>
				                let
				                    head = List.FirstN(items, MaxItems + 1),
				                    shown = List.FirstN(head, MaxItems),
				                    parts = List.Transform(List.Positions(shown), (i) => Safe(() => shown{i})),
				                    more = if List.Count(head) > MaxItems then {"..."} else {}
				                in
				                    "{" & Text.Combine(parts & more, ", ") & "}",
				            TableText = (t as table) as text =>
				                let
				                    head = Table.FirstN(t, MaxItems + 1),
				                    shown = Table.FirstN(head, MaxItems),
				                    columns = Table.ColumnNames(t),
				                    rows = List.Transform(Table.ToRecords(shown), (r) =>
				                        "{" & Text.Combine(List.Transform(columns, (c) => Safe(() => Record.Field(r, c))), ", ")
				                            & "}"),
				                    more = if Table.RowCount(head) > MaxItems then {"..."} else {}
				                in
				                    "#table(type " & TypeText(Value.Type(t)) & ", {" & Text.Combine(rows & more, ", ") & "})",
				            Render = (v as any) as text =>
				                if v is null then "null"
				                else if v is logical then (if v then "true" else "false")
				                else if v is number then Num(v)
				                else if v is text then Quote(v)
				                else if v is date then
				                    "#date(" & Text.Combine(List.Transform({Date.Year(v), Date.Month(v), Date.Day(v)}, Num), ", ") & ")"
				                else if v is datetimezone then
				                    "#datetimezone(" & Text.Combine(List.Transform({Date.Year(v), Date.Month(v), Date.Day(v),
				                        Time.Hour(v), Time.Minute(v), Time.Second(v),
				                        DateTimeZone.ZoneHours(v), DateTimeZone.ZoneMinutes(v)}, Num), ", ") & ")"
				                else if v is datetime then
				                    "#datetime(" & Text.Combine(List.Transform({Date.Year(v), Date.Month(v), Date.Day(v),
				                        Time.Hour(v), Time.Minute(v), Time.Second(v)}, Num), ", ") & ")"
				                else if v is time then
				                    "#time(" & Text.Combine(List.Transform({Time.Hour(v), Time.Minute(v), Time.Second(v)}, Num), ", ") & ")"
				                else if v is duration then
				                    "#duration(" & Text.Combine(List.Transform({Duration.Days(v), Duration.Hours(v),
				                        Duration.Minutes(v), Duration.Seconds(v)}, Num), ", ") & ")"
				                else if v is binary then
				                    "#binary({" & Text.Combine(List.Transform(Binary.ToList(v), Num), ", ") & "})"
				                else if v is list then ListText(v)
				                else if v is record then
				                    "[" & Text.Combine(List.Transform(Record.FieldNames(v), (f) =>
				                        Ident(f) & " = " & Safe(() => Record.Field(v, f))), ", ") & "]"
				                else if v is table then TableText(v)
				                else if v is type then "type " & TypeText(v)
				                else if v is function then FunctionTypeText(Value.Type(v))
				                else "<" & Primitive(Value.Type(v)) & ">",
				            // Separate Expression.Evaluate calls share cached values: with the same #table literal in
				            // two cases, Table.TransformColumnNames in one made Table.Buffer in the other return the
				            // renamed columns (reproduced 2026-09-29; one query with both steps is not affected). A
				            // distinct environment per case is meant to keep each evaluation to itself.
				            Run = (i as number, code as text) as text =>
				                let r = try Render(Expression.Evaluate(code, Environment & [#"__runner case" = i])) in
				                    if r[HasError] then ErrorText(r[Error]) else r[Value],
				            Result = #table(
				                type table [seq = Int64.Type, id = text, result = text],
				                List.Transform(List.Positions(Cases), (i) => {i, Cases{i}{0}, Run(i, Cases{i}{1})})
				            )
				        in
				            Result,
				    Pages = #table(type table [seq = Int64.Type, Function = text, Block = Int64.Type, Code = text, Recorded = text], {{0, "Text.AfterDelimiter", 1, "{Text.AfterDelimiter(""111-222-333"", ""-""), Text.AfterDelimiter(""111-222-333"", ""-"", {0, RelativePosition.FromEnd})}", "{""222-333"", ""333""}"}, {1, "Text.BeforeDelimiter", 1, "Text.BeforeDelimiter(""111-222-333"", ""-"", 1)", """111-222"""}, {2, "Text.BetweenDelimiters", 1, "Text.BetweenDelimiters(""a (b) c (d)"", ""("", "")"", 1)", """d"""}, {3, "Text.Clean", 1, "Text.Clean(""a#(#)(lf)b#(#)(tab)c"")", """abc"""}, {4, "Text.Combine", 1, "Text.Combine({""a"", null, ""b""}, "", "")", """a, b"""}, {5, "Text.Lower", 1, "Text.Lower(""ÀBC"")", """àbc"""}, {6, "Text.PadEnd", 1, "Text.PadEnd(""7"", 3, ""."")", """7.."""}, {7, "Text.PadStart", 1, "{Text.PadStart(""7"", 3, ""0""), Text.PadStart(""1234"", 3, ""0"")}", "{""007"", ""1234""}"}, {8, "Text.Proper", 1, "Text.Proper(""mcDONALD o'brien"")", """Mcdonald O'Brien"""}, {9, "Text.Repeat", 1, "Text.Repeat(""ab"", 3)", """ababab"""}, {10, "Text.Reverse", 1, "Text.Reverse(""abc"")", """cba"""}, {11, "Text.Split", 1, "Text.Split(""a,,b"", "","")", "{""a"", """", ""b""}"}, {12, "Text.SplitAny", 1, "Text.SplitAny(""a,b;c"", "",;"")", "{""a"", ""b"", ""c""}"}, {13, "Text.Trim", 1, "{Text.Trim(""  a  ""), Text.Trim(""--a--"", ""-"")}", "{""a"", ""a""}"}, {14, "Text.TrimEnd", 1, "Text.TrimEnd(""a000"", ""0"")", """a"""}, {15, "Text.TrimStart", 1, "Text.TrimStart(""000123"", ""0"")", """123"""}, {16, "Text.Upper", 1, "{Text.Upper(""abc""), Text.Upper(""straße"")}", "{""ABC"", ""STRAßE""}"}}),
				    Joined = Table.NestedJoin(Pages, "seq", Table.TransformColumns(Live, {{"id", Number.From}}), "id", "L", JoinKind.LeftOuter),
				    Expanded = Table.ExpandTableColumn(Joined, "L", {"result"}, {"Live"}),
				    Matched = Table.AddColumn(Expanded, "Match", each if [Live] = [Recorded] then "yes" else "NO", type text),
				    Sorted = Table.Sort(Matched, {{"seq", Order.Ascending}})
				in
				    Sorted

	annotation PBI_ResultType = Table
