<!-- lab: desktop 2.157.879.0 -->

# Table.Repeat

The rows, three times.

```m
Table.Repeat(#table({"a"}, {{1}}), 3)
```

```text
#table(type table [a = any], {{1}, {1}, {1}})
```
